SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "TEAM ROCKET is gone.\n"
	.string "But you didn't save the day.$"

SilphCo_4F_Text_Grunt1Intro::
    .string "TEAM ROCKET has taken control\n"
    .string "of SILPH CO. again!\p"
	.string "Like we are programmed to!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "You can face GIOVANNI on top,\n"
	.string "but that won't make you a hero.$"
	
SilphCo_4F_Text_RodneyIntro::
    .string "My POKéMON is my loyal servant.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Darn!\n"
    .string "You weak POKéMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "I hope you get lost here.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Knockoff kid spotted!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Who are you?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "Your little disguise isn't\n"
	.string "fooling anyone here. Scram!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "3F$"

