FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "WARDEN: Hi!\p"
    .string "Let me guess, you're here for\n"
    .string "HM03 and HM04?$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Well, I don't give those out\n"
    .string "to any wannabe trainer children.\p"
	.string "HM04 contains STRENGTH.\n"
	.string "Something you lack and'll never learn.\p"
	.string "Now scram and give up on your\n"
	.string "journey. Ha!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "No?\n"
    .string "Good. Quit playing right now.$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} gave the GOLD TEETH\n"
    .string "to the WARDEN.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "The WARDEN popped in his teeth!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "WARDEN: Thanks, son!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "WARDEN: Thank you, lassie!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} took the HM04!$"

FuchsiaCity_WardensHouse_Text_ReceivedHM03FromWarden::
    .string "{PLAYER} took the HM03!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "WARDEN: Stealing our HMs, huh?\p"
    .string "Well, inside HM04, you'll find\n"
    .string "something you lack.\l"
    .string "It lets POKéMON move boulders.\p"
    .string "HM03 lets you get to CINNABAR.\n"
    .string "It erupted, but there is a new tunnel.$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "POKéMON photos and fossils are on\n"
    .string "display.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Old POKéMON merchandise is on\n"
    .string "display.$"

