RockTunnel_B1F_Text_SofiaIntro::
    .string "Do you know how you can avoid\n"
    .string "getting lost in the mountains?\p"
    .string "You can bend twigs as trail\n"
    .string "markers. I told him that once.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "I did my best.$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "I want to go home!\n"
	.string "…Please. Come home.$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Can you beat my power?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Oops!\n"
    .string "Outmuscled!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "I go for power because I hate\n"
    .string "thinking about our loss.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "You have a costume of him?\n"
    .string "I want one, too.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Shoot!\n"
    .string "I am so jealous!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "When you finish your journey,\n"
    .string "can I have it?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Um… You know a lot about POKéMON\n"
    .string "cosplay. Nice suit!$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Well, that's that.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "We all miss him.\n"
    .string "Come home.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "My POKéMON techniques will leave\n"
    .string "you crying!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "I give!\n"
    .string "You're a better technician!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "In mountains, you'll often find\n"
    .string "ZUBAT and ROCK POKéMON.\p"
	.string "You'll also find him.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "I don't often come here, but I will\n"
    .string "battle you.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Oh!\n"
    .string "I lost!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "I like all POKéMON.\n"
    .string "He taught me to.$"

RockTunnel_B1F_Text_EricIntro::
    .string "Hit me with your best shot!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Fired away!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "I'll raise my POKéMON to beat\n"
    .string "yours, kid.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "I draw illustrations of him\n"
    .string "when I'm home.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Whew…\n"
    .string "I'm exhausted…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "I'll go home to draw him.$"

