CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear POKéMON keep me company.\n"
    .string "MEOWTH even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my TEA?\l"
    .string "Are you from PALLET TOWN?\p"
    .string "A boy from PALLET enjoyed TEA\n"
    .string "every day. He visited the CELADON\p"
    .string "DEPT. STORE to buy TEA. But, one\n"
    .string "day, he vanished. I blame you.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"

