CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "A POKé FLUTE awakens sleeping\n"
    .string "POKéMON. You know that. He knew that.\p"
    .string "It does so with a sound that only\n"
    .string "they can hear.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "I rode here from FUCHSIA.\p"
    .string "It's an uphill ride on CYCLING\n"
    .string "ROAD, so I'm exhausted.\l"
	.string "I wonder if he felt like this?$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "If I had a BIKE, I would go to\n"
    .string "CYCLING ROAD!$"

