MtMoon_1F_Text_MarcosIntro::
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!\l"
	.string "Huh… you, look a lot like him.$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Wow!\n"
    .string "Defeated by a copy!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.\l"
    .string "But he can go wherever he wants.$"

MtMoon_1F_Text_JoshIntro::
    .string "Did you come to explore the cave,\n"
    .string "too?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Losing stinks!\n"
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "I came all the way down here to\n"
    .string "show off to girls.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! It's way smaller in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "I lost it!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "The new MT. MOON is boring.\n"
    .string "I'm going back home!$"

MtMoon_1F_Text_JovanIntro::
    .string "What!\n"
    .string "Don't sneak up on me!$"

MtMoon_1F_Text_JovanDefeat::
    .string "My POKéMON won't do!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "I have to find stronger POKéMON.\n"
    .string "Where might they be?$"

MtMoon_1F_Text_IrisIntro::
    .string "What?\n"
    .string "I'm waiting for him.$"

MtMoon_1F_Text_IrisDefeat::
    .string "Buzz off, you little copy!$"

MtMoon_1F_Text_IrisPostBattle::
    .string "I'll always wait for him.$"

MtMoon_1F_Text_KentIntro::
    .string "TEAM ROCKET is in the cave.\n"
    .string "Are you one of them?$"

MtMoon_1F_Text_KentDefeat::
    .string "You got me!$"

MtMoon_1F_Text_KentPostBattle::
    .string "They're repeating their\n"
    .string "old crimes for nostalgia's sake.$"

MtMoon_1F_Text_RobbyIntro::
    .string "Are you a ZUBAT? I've seen so\n"
    .string "many I can't tell creatures apart\l"
	.string "anymore.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "You're not a ZUBAT. Even worse!\n"
	.string "You're mocking our hero!$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "Leave.$"
	
MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Beware!\n"
    .string "ZUBAT is a bloodsucker!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hi, I'm excavating for fossils here\n"
    .string "under MT. MOON.\p"
    .string "Sometimes, BROCK of PEWTER GYM\n"
    .string "lends me a hand.$"

MtMoon_2F_Text_MiguelIntro::
    .string "No! Don't attack me!\n"
    .string "He found the fossil!\l"
    .string "I sold mine!$"

MtMoon_2F_Text_MiguelDefeat::
    .string "I don't have any.\n"
    .string "Buzz off, copycat.$"

MtMoon_2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on CINNABAR ISLAND,\n"
    .string "there was a POKéMON LAB.\p"
    .string "They did research on regenerating\n"
    .string "fossils. Now it's all gone.$"

MtMoon_2F_Text_Grunt1Intro::
    .string "We, TEAM ROCKET, shall find the\n"
    .string "fossils!\p"
    .string "He probably has't found them all!$"

MtMoon_2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_2F_Text_Grunt1PostBattle::
    .string "You made me mad!\n"
    .string "Even we at TEAM ROCKET think you're\l"
	.string "worse than that damn punk RED!$"

MtMoon_2F_Text_Grunt2Intro::
    .string "Ah, the good old days of our pride\n"
	.string "in KANTO, and fighting him...$"

MtMoon_2F_Text_Grunt2Defeat::
    .string "I blew it!$"

MtMoon_2F_Text_Grunt2PostBattle::
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_2F_Text_Grunt3Intro::
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_2F_Text_Grunt3Defeat::
    .string "So, you are good…$"

MtMoon_2F_Text_Grunt3PostBattle::
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_2F_Text_Grunt4Intro::
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "We already dealt with one!$"

MtMoon_2F_Text_Grunt4Defeat::
    .string "I'm steamed!$"

MtMoon_2F_Text_Grunt4PostBattle::
    .string "POKéMON lived here long before\n"
    .string "people came.$"
