PokemonMansion_B1F_Text_LewisIntro::
    .string "Uh-oh…\n"
    .string "Where is he now?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Awooh!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "You can find stuff lying around.\n"
    .string "Past visitors must've left them.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Please quit playing now.\n"
    .string "This is not your game.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "What was that for?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "I don't like you here.\n"
    .string "Please leave.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Diary: Sept. 1\n"
    .string "MEWTWO is far too powerful.\p"
    .string "We have failed to curb its vicious\n"
    .string "tendencies…$"

