PokemonTower_7F_Text_Grunt1Intro::
    .string "What do you want?\n"
    .string "Why are you here? Who are you?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "I give up!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "I'm not going to forget this!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "This old guy marched right up to\n"
    .string "our HIDEOUT.\p"
    .string "Then, he starts ranting about how\n"	
    .string "we killed a RATICATE. We didn't.\p"
    .string "So, we're just talking it over as\n"
    .string "adults.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Please!\n"
    .string "No more!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "POKéMON are only good for making\n"
    .string "money. Why not use them?\p"
    .string "You stay out of his story!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "You're not saving anyone, kid!\n"
	.string "Not even him!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Don't fight anyone! Just quit!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "You're not getting away with this!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Heh?\n"
    .string "You came to save me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "a RATICATE.\p"
    .string "I think it's spirit has\n"
    .string "finally left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, POKéMON\n"
    .string "HOUSE, at the foot of this tower.$"

