PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Yes, yes.\n"
    .string "It's ¥50 for a child's ticket.\p"
    .string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Come again!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Right, ¥50!\n"
    .string "Thank you!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "You don't have enough money.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Please enjoy yourself.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "You can't sneak in the back way!\n"
    .string "Nice try, kid, but no.\p"
    .string "He'd already done that.\n"
    .string "We gave him a FOSSIL.$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "He ressurected it at a LAB.\n"
    .string "Now it's all gone.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "AMBER is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard AMBER.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "I just feel selfish, I'd give my years\n"
    .string "to him if he were still alive.$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "I have no fossils left.\n"
    .string "Please leave now.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} received the OLD AMBER\n"
    .string "from the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Ssh!\n"
    .string "Get the OLD AMBER checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "We have two fossils of rare,\n"
    .string "prehistoric POKéMON on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "There is a beautiful piece of\n"
    .string "AMBER in a clear gold color.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "AERODACTYL Fossil\n"
    .string "A primitive and rare POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "KABUTOPS Fossil\n"
    .string "A primitive and rare POKéMON.$"

