VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my PIDGEY to fly a\n"
    .string "letter to SAFFRON in the north.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI,\n"
    .string "I saw a boy today.\p"
    .string "He looks just like him.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "I send my PIDGEY to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"

