Text_SeismicTossTeach::
    .string "The secrets of space…\n"
    .string "The mysteries of earth…\p"
    .string "There are so many things about\n"
    .string "which we know so little.\p"
    .string "But that should spur us to study\n"
    .string "harder, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about SEISMIC TOSS?\n"
    .string "Should I teach that to a POKéMON?$"

Text_SeismicTossDeclined::
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "MOON STONE, huh?\p"
    .string "He used it to get a CLEFABLE.\n"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "February 27, 1996!\n"
    .string "He began his adventure that day.\p"
    .string "I bought a GAME BOY just so I\n"
    .string "could watch that news.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "This month, we're running a space\n"
    .string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "I want a PIKACHU!\n"
    .string "He trained one! It was so cute!\p"
    .string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Yeah, a PIKACHU soon, I promise!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "SPACE SHUTTLE, CALIFORNIA$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "It's a MOON STONE.$"

