Route20_Text_BarryIntro::
    .string "The water is shallow here.\n"
    .string "There are many people swimming.$"

Route20_Text_BarryDefeat::
    .string "Splash!$"

Route20_Text_BarryPostBattle::
    .string "I wish I could ride my POKéMON.\n"
    .string "I bet you're tired? Good!$"

Route20_Text_ShirleyIntro::
    .string "SEAFOAM is a quiet getaway\n"
    .string "from the sadness of KANTO.\l"
	.string "I'm vacationing here.$"

Route20_Text_ShirleyDefeat::
    .string "Quit playing! You're a FAKE!$"

Route20_Text_ShirleyPostBattle::
    .string "There's a huge cavern underneath\n"
    .string "this island. He's not there, though.$"

Route20_Text_TiffanyIntro::
    .string "I love floating with the fishes\n"
    .string "here among the waves.$"

Route20_Text_TiffanyDefeat::
    .string "Yowch!$"

Route20_Text_TiffanyPostBattle::
    .string "Want to float with me?\n"
	.string "It should help forget about our\l"
	.string "tragedy.$"

Route20_Text_IreneIntro::
    .string "Are you on vacation, too?$"

Route20_Text_IreneDefeat::
    .string "No mercy at all for fakes like you!$"

Route20_Text_IrenePostBattle::
    .string "SEAFOAM used to be a single island\n"
    .string "in the distant past.$"

Route20_Text_DeanIntro::
    .string "Check out my buff physique!$"

Route20_Text_DeanDefeat::
    .string "Wimpy!$"

Route20_Text_DeanPostBattle::
    .string "I should've been buffing up my\n"
    .string "POKéMON, not me!\p"
	.string "Quit wearing his face or I'll\n"
	.string "kick you in the hindquarters!$"

Route20_Text_DarrinIntro::
    .string "Why are you riding a POKéMON?\n"
    .string "Can't you swim?$"

Route20_Text_DarrinDefeat::
    .string "Ouch!\n"
    .string "Torpedoed!$"

Route20_Text_DarrinPostBattle::
    .string "Riding a POKéMON sure looks fun!$"

Route20_Text_RogerIntro::
    .string "I rode my bird POKéMON here.$"

Route20_Text_RogerDefeat::
    .string "Oh, no!\n"
    .string "Now what am I to do?$"

Route20_Text_RogerPostBattle::
    .string "My birds are exhausted.\n"
    .string "They can't FLY me back!$"

Route20_Text_NoraIntro::
    .string "My boyfriend gave me big pearls.$"

Route20_Text_NoraDefeat::
    .string "Oh, no!\n"
    .string "My pearls were in them!$"

Route20_Text_NoraPostBattle::
    .string "Will my pearls grow bigger inside\n"
    .string "CLOYSTER?$"

Route20_Text_MissyIntro::
    .string "I swam here from CINNABAR ISLAND.\n"
    .string "It wasn't easy, I tell you.$"

Route20_Text_MissyDefeat::
    .string "I'm so disappointed!$"

Route20_Text_MissyPostBattle::
    .string "A new tunnel was dug out by BLAINE\n"
    .string "on CINNABAR.\p"
    .string "He calls it the POKéMON TUNNEL.\n"
	.string "It is also a graveyard.$"

Route20_Text_MelissaIntro::
    .string "CINNABAR, in the west, had a LAB\n"
    .string "for POKéMON.\p"
    .string "Now it doesn't anymore.$"

Route20_Text_MelissaDefeat::
    .string "Wait!\n"
    .string "You're supposed to wait!$"

Route20_Text_MelissaPostBattle::
    .string "CINNABAR is a volcanic island.\p"
    .string "All the years of scientific\n"
    .string "research were destroyed when\l"
	.string "a volcano erupted. I blame you.$"

Route20_Text_SeafoamIslands::
    .string "SEAFOAM ISLANDS$"

Route20_Text_MistyTrainsHere::
    .string "Strong TRAINERS and WATER POKéMON\n"
    .string "are common sights in these parts.\p"
    .string "They say that he trains here.$"
