SilphCo_2F_Text_ConnorIntro::
    .string "Help!\n"
    .string "I'm a SILPH employee.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "You knew I was a ROCKET because\n"
    .string "you're just copying his story.$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "I work for both SILPH and TEAM\n"
    .string "ROCKET. You know that. He knew that.$"

SilphCo_2F_Text_JerryIntro::
    .string "It's off-limits here!\n"
    .string "...Come home.$"

SilphCo_2F_Text_JerryDefeat::
    .string "You suck.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Can you solve the maze in here?\n"
    .string "It's easy, I tell you! He did it.$"

SilphCo_2F_Text_Grunt1Intro::
    .string "No kids are allowed in here!\n"
	.string "Not even he was!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Tough!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Diamond-shaped tiles are teleport\n"
    .string "blocks.\p"
    .string "They're transporters for this\n"
    .string "high-tech building.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hey, kid!\n"
	.string "Who are you?\p"
    .string "What are you wandering here for?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "I goofed!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. was associated with\n"
    .string "TEAM ROCKET! Then he came.$"

Text_ThunderWaveTeach::
    .string "Eeek!\n"
    .string "Help! Please! Save us from them!\p"
    .string "Oh, you're not him.\n"
    .string "I'm sorry, I thought…$"
	
Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "But THUNDER WAVE is convenient…$"

Text_ThunderWaveWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE causes paralysis in\n"
    .string "the target POKéMON.\p"
    .string "A paralyzed POKéMON may be unable\n"
    .string "to move in battle.\p"
    .string "It's an ELECTRIC-type move, so it\n"
    .string "won't work on some POKéMON.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "2F$"

