SilphCo_2F_Text_ConnorIntro::
    .string "Help!\n"
    .string "I'm a SILPH employee.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "You knew I was a ROCKET because\n"
    .string "you're just copying his story.$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "I work for both SILPH and TEAM\n"
    .string "ROCKET. You know that. He knew that.$"

SilphCo_2F_Text_JerryIntro::
    .string "It's off-limits here!\n"
    .string "...Come home.$"

SilphCo_2F_Text_JerryDefeat::
    .string "You suck.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Can you solve the maze in here?\n"
    .string "It's easy, I tell you! He did it.$"

SilphCo_2F_Text_Grunt1Intro::
    .string "No kids are allowed in here!\n"
	.string "Not even he was!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Tough!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Diamond-shaped tiles are teleport\n"
    .string "blocks.\p"
    .string "They're transporters for this\n"
    .string "high-tech building.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hey, kid!\n"
	.string "Who are you?\p"
    .string "What are you wandering here for?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "I goofed!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. was associated with\n"
    .string "TEAM ROCKET! Then he came.$"

Text_ThunderWaveTeach::
    .string "Eeek!\n"
    .string "Help! Please! Save us from them!\p"
    .string "Oh, you're not him.\n"
    .string "I'm sorry, I thought…$"
	
Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "But THUNDER WAVE is convenient…$"

Text_ThunderWaveWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE causes paralysis in\n"
    .string "the target POKéMON.\p"
    .string "A paralyzed POKéMON may be unable\n"
    .string "to move in battle.\p"
    .string "It's an ELECTRIC-type move, so it\n"
    .string "won't work on some POKéMON.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "2F$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: What kept you, {PLAYER}?\n"
	.string "Too busy living someone else's life?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: I knew you'd come here.\n"
    .string "I know this story. It isn't yours.\p"
    .string "Give up.\n"
    .string "I'm begging you.$"

SilphCo_7F_Text_RivalDefeat::
    .string "Goddamn it!\n"
    .string "You aren't ready to give up.$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "…{PLAYER}.\n"
    .string "Are you really so selfish?\p"
    .string "How dare you look like him, dress\n"
    .string "like him, and act like him, when\l"
    .string "you're absolutely nothing like him!\p"
    .string "I won't give up.\n"
    .string "I won't let you take this from him.$"

SilphCo_3F_Text_WhatAmIToDo::
    .string "I work for SILPH CO.\n"
    .string "He will save us soon.$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "You and your POKéMON saved us!\p"
	.string "Just kidding. You didn't.\n"
	.string "He did.$"

SilphCo_3F_Text_GruntIntro::
    .string "Quit messing with our world, kid!$"

SilphCo_3F_Text_GruntDefeat::
    .string "I give up!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "A hint? Not giving you any!$"

SilphCo_3F_Text_JoseIntro::
    .string "I support TEAM ROCKET more than\n"
    .string "I support SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "You really got me!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "TEAM ROCKET said that if I helped\n"
    .string "them, they'd let me go on a mountain.$"
