Route21_South_Text_JackIntro::
	.string "I caught my POKéMON at sea.$"

Route21_South_Text_JackDefeat::
	.string "Diver!!\n"
	.string "Down!!$"

Route21_South_Text_JackPostBattle::
	.string "How did you catch his POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "Right now, I'm in a triathlon meet.$"

Route21_South_Text_JeromeDefeat::
	.string "Pant…\n"
	.string "Pant… Pant…$"

Route21_South_Text_JeromePostBattle::
	.string "I'm beat! But, I still have the\n"
	.string "bike race and marathon left!$"

Route21_South_Text_RolandIntro::
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"

Route21_South_Text_RolandDefeat::
	.string "Yow!\n"
	.string "I lost!$"

Route21_South_Text_RolandPostBattle::
	.string "I'm sunburnt to a crisp!\n"
	.string "The nearby volcano doesn't help.$"

Route21_South_Text_ClaudeIntro::
	.string "Hey, don't wear his face like that!$"

Route21_South_Text_ClaudeDefeat::
	.string "Sorry! I'm just so frustrated over\n"
	.string "him still not being found.$"

Route21_South_Text_ClaudePostBattle::
	.string "Sheesh, I haven't caught a thing.\p"
	.string "Could this place actually be\n"
	.string "programmed to not catch\l"
	.string "anything?$"

Route21_South_Text_NolanIntro::
	.string "You're him, aren't you?\n"
	.string "Keep me company!$"

Route21_South_Text_NolanDefeat::
	.string "You're not him.\n"
	.string "But at least I had somebody\l"
	.string "to spend time with. Thanks!$"

Route21_South_Text_NolanPostBattle::
	.string "Oh wait!\n"
	.string "I got a bite! Yeah!$"

Route21_North_Text_LilIntro::
	.string "LIL: Huh? A battle?\n"
	.string "IAN, can't you do it alone?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Oh, see?\n"
	.string "We lost, just as programmed.\l"
	.string "And it's not even to him!$"

Route21_North_Text_LilPostBattle::
	.string "LIL: I'm tired.\n"
	.string "Can't we go home already?\p"
	.string "We already got scammed by\n"
	.string "a copycat!$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: Huh? A battle?\n"
	.string "I can't be bothered to do it alone.\l"
	.string "Bring two POKéMON, won't you?$"

Route21_North_Text_IanIntro::
	.string "IAN: My sis wallows in despair\n"
	.string "over the loss, so I made her come.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Awww, Sis!\n"
	.string "Get it together!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Come on, Sis!\p"
	.string "You're not going to get happy\n"
	.string "like this!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: We want a two-on-two battle.\n"
	.string "So can you bring two POKéMON?$"
