FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "A mere child like you dares to\n"
    .string "challenge me?\p"
    .string "The very idea makes me shiver\n"
    .string "with mirth!\p"
    .string "Only one child ever stood a chance\n"
    .string "against me! And you're not him.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph!\n"
    .string "You have proven your worth!\p"
    .string "Here!\n"
    .string "Take the SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "When afflicted by TOXIC, a POKéMON\n"
    .string "suffers more and more.\p"
    .string "It suffers worsening damage as the\n"
    .string "battle wears on!\p"
    .string "It will surely terrorize foes!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Now that you have the SOULBADGE,\n"
    .string "the DEFENSE of your POKéMON rises.\p"
    .string "It also lets you SURF outside of\n"
    .string "battle.\p"
    .string "Ah!\n"
    .string "Take this, too!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} received TM06\n"
    .string "from KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Sealed within that TM06 lies\n"
    .string "TOXIC!\p"
    .string "It is a secret technique dating\n"
    .string "back some four hundred years.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Strength isn't the key for POKéMON.\n"
    .string "Do you understand this?\l"
	.string "I know you do. Because he did.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "What?\n"
    .string "Extraordinary!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "So, you mix brawn with brains?\n"
    .string "Good strategy!\p"
    .string "That's remarkable for a little kid.\n"
	.string "I only saw one other person that\n"
	.string "skilled. Him.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "I was a magician once upon a time.\p"
    .string "But I dreamt of becoming a ninja,\n"
    .string "so I joined this GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "I'm done for!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Even though I've lost, I will keep\n"
    .string "training according to the teachings\l"
    .string "of the TRAINER from PALLET.\l"
	.string "That's not you, though.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Let's see you beat my special\n"
    .string "techniques! It'd be so cool!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "You had me fooled! You're not him.$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "I like poison and sleep techniques,\n"
    .string "as they hurt wannabe children like\l"
	.string "you the most!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop right there!\p"
    .string "The maze of the FUCHSIA GYM\n"
    .string "have you annoyed? Good!$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "You still don't measure up!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "You impressed me!\n"
    .string "\p"
    .string "Haha. No. He did all of this\n"
    .string "before you. This isn't new.$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "I also study the way of the boy\n"
    .string "with Master KOGA!\p"
    .string "The boy had a long history of using\n"
    .string "animals!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "I still have much to learn.\n"
	.string "And so do you.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Master KOGA comes from a long line\n"
    .string "of ninjas. He came from PALLET.\p"
    .string "What did you descend from?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Drats!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Where there is light, there is\n"
    .string "shadow\p"
    .string "Light and shadow!\n"
    .string "Which do you choose?\l"
	.string "He chose the right path.$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Liar in the making!\p"
    .string "FUCHSIA GYM is a tricked-up place.\n"
    .string "It's riddled with invisible walls!\p"
    .string "KOGA might appear close, but he's\n"
    .string "blocked off.\p"
    .string "You have to find gaps in the walls\n"
    .string "to reach him.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "It's amazing how even copycats can\n"
    .string "beat ninjas these days!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED, {PLAYER}$"

