SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "I wonder if he is dead…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "Thanks for saving us!\p"
	.string "...But he did it first.$"

SilphCo_8F_Text_Grunt1Intro::
    .string "That's as far as you'll go!\n"
	.string "You will not be him.$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "Not enough grit!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "If you don't quit playing…\n"
    .string "I'll call for backup!$"

SilphCo_8F_Text_ParkerIntro::
    .string "You're causing our world problems!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "Huh?\n"
    .string "I lost?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "So, what do you think?\n"
    .string "Do you hate him?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "Whoo!\n"
    .string "Oh, Brothers!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "I'll leave you up to my brothers.$"

SilphCo_8F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "8F$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "TEAM ROCKET's BOSS is terribly\n"
    .string "cruel!\p"
    .string "To him, POKéMON are just tools to\n"
    .string "be used.\p"
    .string "That tyrant took over SILPH, but\n"
    .string "he came along and stopped him.\p"
	.string "You won't measure up, though. Quit.$"
