SSAnne_2F_Room4_Text_LamarIntro::
    .string "Which do you find more worthy,\n"
    .string "a strong or a rare POKéMON?\p"
    .string "He placed worth on all POKéMON\n"
	.string "That's why he was such a good trainer.$"


SSAnne_2F_Room4_Text_LamarDefeat::
    .string "I must salute you!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "I used to prefer strong and\n"
    .string "rare POKéMON. Then I met him.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "I don't believe I saw you at the\n"
    .string "party?\p"
	.string "I know I've seen you before though…$" 

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Take it easy!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Oh, I adore your strong POKéMON!\n"
    .string "Oh, how I envy you for them!$"

