CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "SUPER REPEL keeps weak POKéMON at\n"
    .string "bay…\p"
    .string "Hmm, it's a more powerful REPEL.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "For long outings, you should buy\n"
    .string "REVIVE.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Top-Grade Items for TRAINERS!\p"
    .string "2F: TRAINER'S MARKET$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "We had a customer who occasionally\n"
    .string "came.\p"
    .string "He always bought red and white caps.\n"
    .string "I wonder… Will he ever come home?$"
