SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "TEAM ROCKET is in an uproar over\n"
    .string "some intruder.\p"
    .string "That's you, right? How lame.\n"
	.string "I thought it was him.$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "TEAM ROCKET took off!\n"
    .string "You're our hero! Thank you!\l"
	.string "… … … ……\l"
	.string "…Not! He is, you're just copying him.$"

SilphCo_5F_Text_Grunt1Intro::
    .string "I heard he was wandering\n"
    .string "around. But it's just a kid!$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Boom!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "It's not smart to pick a fight with\n"
    .string "TEAM ROCKET!\p"
	.string "He may have outsmarted us, but you won't!$"

SilphCo_5F_Text_BeauIntro::
    .string "We are working on a better MASTER BALL on\n"
    .string "this floor! They ain't for you, though!$"

SilphCo_5F_Text_BeauDefeat::
    .string "Dang!\n"
    .string "Blast it!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "We are working on a new MASTER\n"
    .string "BALL to deliver to people like him.$"

SilphCo_5F_Text_DaltonIntro::
    .string "Whaaat?\p"
    .string "There shouldn't be any children\n"
    .string "here! Even if they have his face!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Oh, goodness!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "You're only on 5F.\n"
    .string "It's a long way to my BOSS!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Show KANTO a little respect!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Cough…\n"
    .string "Cough…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Which reminds me.\p"
    .string "You aren't him.$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "It's a POKéMON REPORT!\p"
    .string "POKéMON TRAINER RED has went missing.\n"
    .string "He was last seen heading to a mountain.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "It's a POKéMON REPORT!\p"
    .string "An expedition to MT.SILVER has\n"
    .string "begun to try and retrieve him.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "It's a POKéMON REPORT!\p"
    .string "The expedition team calls for\n"
    .string "warm clothing and supplies.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "5F$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Those thugs that took over our\n"
    .string "building…\p"
    .string "Their BOSS said he was looking for\n"
    .string "strong POKéMON.\p"
    .string "I hope our PRESIDENT managed to\n"
    .string "avoid trouble…$"
