LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Who are you?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Did you buy some REVIVES?\n"
    .string "They revive any fainted POKéMON!\p"
	.string "…I wish they'd bring him back too.$"
	
LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Sometimes, a TRAINER duo will\n"
    .string "challenge you with two POKéMON\l"
    .string "at the same time.\p"
    .string "If that happens, you have to send\n"
    .string "out two POKéMON to battle, too.\p"
	.string "He never had a chance to do that.\n"
	.string "I blame you.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
