Text_OnlySkilledTrainersAllowedThrough::
	.string "Only trainers who have proven\n"
	.string "themselves worthy are allowed through.\p"
	.string "You don't have the eight BADGES\n"
	.string "of KANTO yet!$"

Text_CantLetYouPass::
	.string "Rules are rules.\n"
	.string "I can't let you pass.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Oh! That is the {STR_VAR_1}!\n"
	.string "Go right ahead.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Only trainers who are proven\n"
	.string "to be worthy are allowed through.\p"
	.string "You don't have the eight BADGES\n"
	.string "of KANTO yet!\p"
	.string "Rules are rules.\n"
	.string "I can't let you pass.$"
	
Text_OnlyPassWithBadgeOhGoAhead::
	.string "Oh! The eight BADGES of KANTO!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay, then.\n"
	.string "Please, go right ahead.\l"
	.string "Though I wish you wouldn't.$"

Text_OnlyPassWithChampDontHaveYet::
	.string "Only trainers who are proven\n"
	.string "to be worthy are allowed through\l"
	.string "to MT.SILVER.\p"
	.string "You aren't the CHAMPION yet!\n"
	.string "It's too dangerous out there.\p"
	.string "I can't let you pass.$"

Text_OhThatsChampGoRightAhead::
	.string "Oh! So you are CHAMPION!\n"
	.string "You're worthy of entering\l"
	.string "MT. SILVER!\p"
	.string "Go right ahead.\n"
	.string "Save him for all of us.$"