LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?\n"
    .string "Do you believe in him?$"
	
LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "Do you think he's a ghost…?$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "It's silly to think we could ever\n"
    .string "see him again, isn't it?$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of POKéMON.\p"
    .string "It's also a grave site for people.\n"
    .string "He's not here, though.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Ghosts appeared in POKéMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "POKéMON that you killed.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "He realized his mistake here.$"

LavenderTown_Text_SilphScopeNotice::
    .string "Come home.\n"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER VOLUNTEER\n"
    .string "POKéMON HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "This is not a game.$"

