PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "This place is, like, creepy!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "I wonder where my partner went.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "My mentor lives here.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "Whew!\n"
    .string "Overwhelming!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "So, you want to try beating\n"
    .string "BLAINE? He's underground.$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Diary: Feb. 6\n"
    .string "MEW gave birth.\p"
    .string "We named the newborn MEWTWO.$"

