LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "What he did was an accident.\n"
    .string "What you did was murder.$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "I saw a RATICATE die during a\n"
    .string "battle on the S.S ANNE.\p"
    .string "Was that you?$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "You know how the CUBONE species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"

