Route17_Text_RaulIntro::
    .string "There's no getting rich quick in\n"
    .string "battling kids. Not even him.$"

Route17_Text_RaulDefeat::
    .string "Burned out!$"

Route17_Text_RaulPostBattle::
    .string "You can find good stuff lying\n"
    .string "around on CYCLING ROAD.\p"
    .string "There's good money in picking them\n"
    .string "up and selling them.\l"
	.string "I told him that once.$"

Route17_Text_IsaiahIntro::
    .string "I'm mighty proud of my bod, kiddo.\n"
    .string "Come on!$"

Route17_Text_IsaiahDefeat::
    .string "Whoo!$"

Route17_Text_IsaiahPostBattle::
    .string "I could belly-bump you outta\n"
    .string "here, you little wannabe!$"

Route17_Text_VirgilIntro::
    .string "You heading to FUCHSIA?\n"
	.string "You will never be him. Give up.$"

Route17_Text_VirgilDefeat::
    .string "Crash and burn!$"

Route17_Text_VirgilPostBattle::
    .string "I love racing downhill!\n"
	.string "KANTO is also going downhill!$"

Route17_Text_BillyIntro::
    .string "We're BIKERS!\n"
    .string "We rule the roads, man!$"

Route17_Text_BillyDefeat::
    .string "Smoked!$"

Route17_Text_BillyPostBattle::
    .string "Are you looking for adventure?$"

Route17_Text_NikolasIntro::
    .string "Let VOLTORB electrify you!$"

Route17_Text_NikolasDefeat::
    .string "Grounded out!$"

Route17_Text_NikolasPostBattle::
    .string "I got my VOLTORB at the abandoned\n"
    .string "POWER PLANT.$"

Route17_Text_ZeekIntro::
    .string "I saw you and thought you were him,\n"
    .string "but you aren't. Why are you like this?$"

Route17_Text_ZeekDefeat::
    .string "Why, you!$"

Route17_Text_ZeekPostBattle::
    .string "Maybe you should get a face\n"
    .string "of your own and quit playing.$"

Route17_Text_JamalIntro::
    .string "I need a little exercise!\n"
	.string "Like him at the mountains!$"

Route17_Text_JamalDefeat::
    .string "Whew!\n"
    .string "Good workout!$"

Route17_Text_JamalPostBattle::
    .string "I'm sure I lost weight there!$"

Route17_Text_CoreyIntro::
    .string "Be a rebel!\n"
	.string "Continue wearing his face!$"

Route17_Text_CoreyDefeat::
    .string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "Be ready to fight for your\n"
	.string "right to be him!$"

Route17_Text_JaxonIntro::
    .string "Nice BIKE! Just like his!\n"
    .string "Now hand it over!$"

Route17_Text_JaxonDefeat::
    .string "Shoot!$"

Route17_Text_JaxonPostBattle::
    .string "The slope makes it hard to steer.$"

Route17_Text_WilliamIntro::
    .string "Get lost, kid!\n"
    .string "You will not be him!$"

Route17_Text_WilliamDefeat::
    .string "Are you satisfied?\n"
	.string "This is how his story went!$"

Route17_Text_WilliamPostBattle::
    .string "I will stay here as programmed\n"
	.string "to. Now scram and continue mimicking.$"

Route17_Text_WatchOutForDiscardedItems::
    .string "It's a notice.\p"
    .string "Watch out for discarded items.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "TRAINER TIPS\p"
    .string "All POKéMON are unique.\p"
    .string "Even POKéMON of the same species\n"
    .string "and level grow at different rates.$"

Route17_Text_PressBToStayInPlace::
    .string "TRAINER TIPS\p"
    .string "Press the B Button to stay in place\n"
    .string "while on a slope.$"

Route17_Text_RouteSign::
    .string "ROUTE 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
    .string "It's a notice!\p"
    .string "Don't throw the game, throw POKé\n"
    .string "BALLS instead!$"

Route17_Text_CyclingRoadSign::
    .string "CYCLING ROAD\n"
    .string "Slope ends here!$"

