Route12_Text_MonSprawledOutInSlumber::
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Text_SnorlaxWokeUp::
    .string "SNORLAX woke up!\p"
    .string "It attacked in a grumpy rage!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX calmed down.\n"
    .string "It gave a huge yawn…\l"
    .string "And returned to the mountains.$"

Text_WantToUsePokeFlute::
    .string "Want to use the POKé FLUTE?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} played the POKé FLUTE.\n"
	.string "Just like he did.$"

Route12_Text_NedIntro::
    .string "Yeah!\n"
    .string "I got a knockoff here!$"

Route12_Text_NedDefeat::
    .string "Tch!\n"
    .string "Just a small fry…$"

Route12_Text_NedPostBattle::
    .string "Hang on!\n"
    .string "Our story's snagged!$"

Route12_Text_ChipIntro::
    .string "Be patient.\n"
    .string "Fishing is a waiting game.$"

Route12_Text_ChipDefeat::
    .string "That one got away!$"

Route12_Text_ChipPostBattle::
    .string "With a better ROD, I could catch\n"
    .string "better POKéMON…$"

Route12_Text_JustinIntro::
    .string "I'm searching for a MOON STONE.\n"
    .string "He never gave me any.$"

Route12_Text_JustinDefeat::
    .string "Oww!$"

Route12_Text_JustinPostBattle::
    .string "I could have made my POKéMON\n"
    .string "evolve with a MOON STONE.\p"
    .string "I would have won against you then.\n"
	.string "Screw you both!$"

Route12_Text_LucaIntro::
    .string "Electricity is my specialty.\p"
    .string "You should zap sea POKéMON.\n"
    .string "I told him that once.$"

Route12_Text_LucaDefeat::
    .string "Unplugged!$"

Route12_Text_LucaPostBattle::
    .string "I've been slacking off on the job\n"
    .string "because our loss is too sad.$"

Route12_Text_HankIntro::
    .string "The FISHING FOOL versus the\n"
    .string "KNOCKOFF of our boy!$"

Route12_Text_HankDefeat::
    .string "Touch too much!$"

Route12_Text_HankPostBattle::
    .string "I guess you get to be good at\n"
    .string "what you like.\p"
    .string "Well, you beat me at POKéMON,\n"
    .string "but you can't top him at it.$"

Route12_Text_ElliotIntro::
    .string "I love fishing, don't get me wrong.\p"
    .string "But it'd be best if he also came back\n"
    .string "to fish with me.$"

Route12_Text_ElliotDefeat::
    .string "It's not easy…$"

Route12_Text_ElliotPostBattle::
    .string "It's all right.\n"
    .string "Losing doesn't bug me anymore.\l"
	.string "After all, we already lost somebody.$"

Route12_Text_AndrewIntro::
    .string "What's catching?\p"
    .string "You never know what you could\n"
    .string "catch!$"

Route12_Text_AndrewDefeat::
    .string "Lost it!$"

Route12_Text_AndrewPostBattle::
    .string "What, MAGIKARP?\p"
    .string "I catch them all the time, sure.\n"
    .string "But, boy are they wimpy.$"

Route12_Text_RouteSign::
    .string "ROUTE 12 \n"
    .string "North to LAVENDER$"

Route12_Text_SportfishingArea::
    .string "SPORTFISHING AREA$"

Route12_Text_JesIntro::
    .string "JES: If I win, I'm going to\n"
    .string "propose to GIA.$"

Route12_Text_JesDefeat::
    .string "JES: Oh, please, why couldn't you\n"
    .string "let us win?\p"
	.string "More so importantly, you're also\n"
	.string "disrespecting our boy!\p$"
	.string "He never got a chance to double battle!$"

Route12_Text_JesPostBattle::
    .string "JES: Oh, GIA, forgive me,\n"
    .string "my love! I didn't wanna lose to a copy!$"

Route12_Text_JesNotEnoughMons::
    .string "JES: GIA and I, we'll be\n"
    .string "together forever.\p"
    .string "We won't battle unless you have\n"
    .string "a journey of your own.$"

Route12_Text_GiaIntro::
    .string "GIA: Hey, JES…\p"
    .string "If we win, I'll marry you!$"

Route12_Text_GiaDefeat::
    .string "GIA: Oh, but why are you copying his\n"
	.string "every move?$"

Route12_Text_GiaPostBattle::
    .string "GIA: JES, you silly!\n"
    .string "You ruined this! I can't believe\l"
	.string "you'd lose to a knockoff!$"

Route12_Text_GiaNotEnoughMons::
    .string "GIA: I can't bear to battle\n"
    .string "without my JES!\p"
    .string "Don't you have any originality?$"
