SaffronCity_Gym_Text_SabrinaIntro::
    .string "I had a vision of your arrival.\p"
    .string "I have had psychic powers since\n"
    .string "I was a child.\p"
    .string "You were repeating his story, and\n"
    .string "ended up doing a lot of the things\l"
    .string "that he did.\p"
	.string "I dislike battling with copycats, but\n"
    .string "I am obliged to by law!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "This loss shocks me! Copies don't win!\n"
    .string "But, a loss is a loss.\p"
    .string "I admit, I didn't work hard enough\n"
    .string "to win.\p"
    .string "Unfortunately, I have to hand you the\n"
    .string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Everyone has psychic power.\n"
    .string "He was the only one to realize it.\p"
	.string "Now, can you scram out of my GYM?\n"
	.string "I don't like how you wear his face.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "The MARSHBADGE makes POKéMON up\n"
    .string "to Lv. 70 obey you.\p"
    .string "Stronger POKéMON will become wild,\n"
    .string "ignoring your orders in battle.\p"
    .string "Just don't raise your POKéMON too\n"
    .string "much to avoid that problem.\p"
    .string "Wait, please take this TM with you.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} received TM04 from\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "Now please go and pester the other\n"
    .string "GYM LEADERs, just like you wanted to.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Your BAG is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "He was far younger than I,\n"
    .string "but he has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "You don't measure up!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "In a battle of equals, the one\n"
    .string "with less mimicry wins.\p"
    .string "If you wish to be him, focus\n"
    .string "and do something of your own.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Does our decoding power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "I never foresaw a wannabe like you\n"
	.string "actually succeeding!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKéMON feared absolutely\n"
    .string "nothing.\p"
	.string "Then you came along and ruined it.$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMON take on the appearance of\n"
    .string "their TRAINERS.\p"
    .string "Your POKéMON must be weak, then!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "I knew this is how it would go.\n"
	.string "We all know his story.$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "I have much to learn still…\p"
    .string "I must master PSYCHIC and teach it\n"
    .string "to my POKéMON…\p"
	.string "Then we will find his location.$"

SaffronCity_Gym_Text_TyronIntro::
    .string "You don't understand, do you?\p"
    .string "That mimicry alone isn't enough to\n"
    .string "win in the world of POKéMON?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "How can a wannabe like you actually\n"
    .string "win at every battle he did?$"

SaffronCity_Gym_Text_TashaIntro::
    .string "Hey wannabe, your game shall\n"
    .string "end right now!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "I knew that this was going to take\n"
    .string "place, because...\p"
	.string "We are always programmed to lose.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA is young, but she's also\n"
    .string "our highly skilled LEADER.\p"
    .string "You won't reach her easily, because\n"
	.string "you will never be him.$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Ow!\n"
    .string "Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "There used to be a TRAINER smarter\n"
    .string "than even us PSYCHICs.\p"
    .string "He came from PALLET, like you.\n"
    .string "He quickly disappeared though.\p"
    .string "Where, we do not know.\n"
    .string "And you don't either, you wannabe!$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKéMON GYM is famous for\n"
    .string "training psychics.\p"
    .string "You want to be like him, don't\n"
    .string "you? I can tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "That's right! I used telepathy to\n"
    .string "read your mind! It's just like his!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Liar in the making!\p"
    .string "SABRINA's POKéMON use psychic\n"
    .string "power instead of force.\p"
    .string "Liars are especially\n"
    .string "weak against PSYCHIC POKéMON.\p"
    .string "They'll get destroyed before they\n"
    .string "can even utter a word!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psychic power, huh?\p"
    .string "If I had that, I'd rescue him\n"
    .string "from the mountains!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED, {PLAYER}$"

