CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Me?\n"
    .string "I'm the programmer!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "I'm the graphic artist!\n"
    .string "I drew him.$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "I wrote the story!\n"
    .string "Isn't ERIKA cute?\p"
    .string "I like MISTY a lot, too!\n"
    .string "Oh, and SABRINA, I like her!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Is that right?\p"
    .string "I'm the game designer!\p"
    .string "Becoming CHAMPION is tough, but\n"
    .string "don't quit! He managed to.\p"
    .string "When you finish, come tell me!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Excellent!\n"
    .string "You completed your POKéDEX!\l"
    .string "Congratulations!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "It's the game program!\n"
    .string "…It looks different.$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "This isn't you on the screen.$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "It's the script!\n"
    .string "…The ending is wrong…$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK Development Room\n"
	.string "Please bring him back.$"

