SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Oh! Hi! You're not a ROCKET!\n"
    .string "You came to save us?\l"
    .string "Why, thank you!\p"
    .string "I want you to have this POKéMON\n"
    .string "for saving us.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} obtained a LAPRAS from\n"
    .string "the SILPH employee!$"

SilphCo_7F_Text_ExplainLapras::
    .string "It's a LAPRAS.\n"
    .string "It's a very intelligent POKéMON.\p"
    .string "We gave him one too.$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "TEAM ROCKET's BOSS went to the\n"
    .string "boardroom!\p"
    .string "But it's okay.\n"
    .string "He should come back soon.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "TEAM ROCKET was after the MASTER\n"
    .string "BALL 2.0, which catches any POKéMON.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "We canceled the MASTER BALL 2.0\n"
    .string "project because of his disappearance.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "It would be bad if TEAM ROCKET\n"
    .string "took over SILPH and our funds.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "You chased off TEAM ROCKET?\n"
    .string "But he's already done that before.$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "You!\n"
    .string "It's really dangerous here!\p"
    .string "You came to save me?\n"
    .string "You can't!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Thank you so much!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Uh-oh!\n"
    .string "I smell a little copy!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Lights out!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "You can beat us, but that will\n"
    .string "never make you the hero.$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Heheh!\p"
    .string "You mistook me for a SILPH worker?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "I'm done!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Despite your age, you are\n"
    .string "already rotten to the core!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Aack!\n"
    .string "Brothers, I lost!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Doesn't matter.\n"
    .string "My brothers will repay the favor!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "An unoriginal intruder?\n"
    .string "That must be you!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Fine!\n"
    .string "I lost!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Go on home before we all get\n"
    .string "even more pissed off!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "7F$"

