ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Welcome to my hideout!\p"
    .string "It shall be so until I can restore\n"
    .string "TEAM ROCKET to its former glory.\p"
    .string "You found me again. Just like he did.\n"
    .string "But you're not him.\p"
    .string "You shall now lose to GIOVANNI, the\n"
    .string "second greatest TRAINER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "No!\n"
    .string "You're not him!\l"
    .string "But, you have still won!\p"
    .string "Unfortunately, I have to give you the\n"
    .string "EARTHBADGE!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "You and he both managed to defeat me,\n"
    .string "but you will never be him.\p"
    .string "There's still plenty of time for you\n"
    .string "to fail, and you will.\p"
	.string "Just give up already.$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "The EARTHBADGE makes POKéMON of\n"
    .string "any level obey without question.\l"
    .string "That's why he was so strong.\p"
    .string "Also, I have to give you this TM.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} received TM26\n"
    .string "from GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 contains EARTHQUAKE.\p"
    .string "It is a powerful attack that causes\n"
    .string "a massive tremor.\p"
    .string "I made it when I ran the GYM here,\n"
    .string "far too long ago… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space for this!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "You must be running out of steam\l"
    .string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "I ran out of gas!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "You'll need power to keep up with\n"
    .string "our GYM LEADER.\l"
	.string "Which I highly doubt you have.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "I'm raging over our tragedy!\l"
	.string "Quit disrespecting him, or else!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "You're still not worthy!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON and him, they made wonderful\n"
    .string "music together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in tone-deaf harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Do you know the identity of our\n"
    .string "GYM LEADER? You do because he did.$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate is the ultimate form of\n"
    .string "martial arts!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "If my POKéMON were as good at\n"
    .string "karate as I… I'd kick your\l"
	.string "butt out of this story!$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "The truly talented win with style.\n"
	.string "Not by copying others' styles, though!$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "You're not winning!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "He beat me like this too.$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "I'm the KARATE KING!\n"
    .string "Your fate rests with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "The POKéMON LEAGUE?\n"
    .string "You? Don't get cocky!\l"
	.string "You aren't him.$"

ViridianCity_Gym_Text_ColeIntro::
    .string "You will cower at the crack of\n"
    .string "my whip for stealing his story!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Whiplash!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Wait!\n"
    .string "You're still careless?$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM was closed for a\n"
    .string "long time.\p"
    .string "Almost as long he's been gone.$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "I was beaten?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "You can go on to the POKéMON\n"
    .string "LEAGUE only by defeating our GYM\l"
    .string "LEADER, but you will still not\l"
	.string "be him. Give up already.$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Liar in the making!\p"
    .string "The only one who knows the VIRIDIAN\n"
    .string "LEADER's identity is the boy.\p"
    .string "And you aren't him.\n"
    .string "This will be the toughest of all\l"
    .string "the GYM LEADERS.\p"
    .string "Also, I heard that the TRAINERS\n"
    .string "here like GROUND-type POKéMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "GIOVANNI became the GYM LEADER\n"
    .string "of VIRIDIAN? I blame you.$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: ?\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: GIOVANNI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED, {PLAYER}$"

