RocketHideout_B1F_Text_Grunt1Intro::
    .string "Who are you?\n"
    .string "How did you get in our world?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Blast it… You're dissing the\n"
    .string "pride of KANTO, aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "You broke into his story?\n"
    .string "What a nerve! You aren't him.$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "You're not going to get away with\n"
    .string "this, copy!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Unoriginal knockoff boy alert!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "I can't do it!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH SCOPE? Humph!\n"
    .string "GIOVANNI has it.\p"
	.string "But you will not obtain it.\n"
	.string "You will never be him.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Why did you come here?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "…\n"
    .string "Quit playing.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Are you losing, you little copy?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Why…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Uh-oh, that ruckus somehow got\n"
    .string "past us!$"

