Route4_Text_TrippedOverGeodude::
    .string "Ow! I just got attacked by a\n"
    .string "swarm of ZUBATs! I need to head to\l"
	.string "a POKéMON CENTER right away!$"

Route4_Text_CrissyIntro::
    .string "I came to MT. MOON in search of\n"
    .string "a POKéMON TRAINER.$"

Route4_Text_CrissyDefeat::
	.string "You're not him! And this is the\n"
	.string "wrong MOUNTAIN. What was it again?\l"
    .string "MT. GOLD? MT. SAPPHIRE?$"

Route4_Text_CrissyPostBattle::
    .string "After all we did for him!\n"
    .string "You just come and laugh at us.\l$"
    .string "Effing prick.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
    .string "A punch of roaring ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When the chips are down,\n"
    .string "MEGA PUNCH is the ultimate attack!\l"
    .string "You agree, yes?\p"
    .string "Now!\n"
    .string "Let me teach it to your POKéMON!$"

Text_MegaPunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "Fine!\n"
    .string "Which POKéMON will learn it?$"

Text_MegaPunchTaught::
    .string "Now, we are comrades in the way of\n"
    .string "punching!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fool who trains\l"
    .string "only his silly kicking over there.$"

Text_MegaKickTeach::
    .string "A kick of brutal ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When you get right down to it,\n"
    .string "MEGA KICK is the ultimate attack!\l"
    .string "Don't you agree?\p"
    .string "Okay!\n"
    .string "I'll teach it to your POKéMON!$"

Text_MegaKickDeclined::
    .string "You'll come crawling back when you\n"
    .string "realize the value of MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"

Text_MegaKickTaught::
    .string "Now, we are soul mates in the way\n"
    .string "of kicking!\p"
    .string "You should run before you're seen\n"
    .string "by the deluded nitwit who trains\l"
    .string "only simple punching over there.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You just copied his actions,\l"
	.string "didn't you? How original!\p"
    .string "He was cool. He wasn't just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a CHAMPION\n"
    .string "like him.$"
