CeladonCity_Gym_Text_ErikaIntro::
    .string "Hello…\n"
    .string "Lovely weather, isn't it?\l"
    .string "It's so pleasant…\p"
    .string "…Oh, dear…\n"
    .string "I must have dozed off. Welcome.\p"
    .string "My name is ERIKA.\n"
    .string "I am the LEADER of CELADON GYM.\p"
    .string "I am a student of the art of\n"
    .string "flower arranging.\p"
    .string "My POKéMON are solely of the\n"
    .string "GRASS type.\p"
    .string "…Oh, I'm sorry, I had no idea that\n"
    .string "you wished to challenge me.\p"
	.string "…You know, he challenged me too.\n"
    .string "…Very well, but you shall lose.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Oh!\n"
    .string "I concede defeat.\l"
    .string "You are somewhat strong.\p"
    .string "I am unfortunately obliged to\n"
    .string "give you the RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "You are cataloging POKéMON?\n"
    .string "Oh wow, how impressive.\p"
    .string "It seems a lost cause when\n"
    .string "it's already been done.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "The RAINBOWBADGE will make\n"
    .string "POKéMON up to Lv. 50 obey.\p"
    .string "It also allows POKéMON to use\n"
    .string "something you lack out of battle.\p"
    .string "Take this with you and scram.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} received TM19\n"
    .string "from ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 contains GIGA DRAIN.\p"
    .string "It drains life from your POKéMON\n"
	.string "and gives it to yours.\p"
    .string "It seems like you're doing the\n"
    .string "same to his life.$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "You should make room for this.$"

CeladonCity_Gym_Text_KayIntro::
    .string "I should tell you about this GYM.\p"
    .string "Only ladies are allowed in\n"
    .string "here!\p"
	.string "The only boy who went past was him!\n"
	.string "But you ain't him! You're done for!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "You're too rough!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Bleaah!\n"
    .string "I hope ERIKA wipes you out!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Oh, welcome.\n"
    .string "I was getting depressed.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "My makeup!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "Wait, you're not who I thought\n"
    .string "you were.\p"
    .string "Why are you playing cruel jokes\n"
    .string "on us ladies? Sniff…$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Weren't you peeking in here\n"
    .string "earlier?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "You're an eye-opener!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "I thought I recognized you.\n"
    .string "But you only look like him.$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Look, look!\n"
    .string "See my POKéMON!\p"
    .string "I like the GRASS type.\n"
    .string "He taught me they're easy to raise.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "We only use GRASS-type POKéMON at\n"
    .string "our GYM.\p"
    .string "We also use them to make\n"
    .string "flower arrangements in honor of him.$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Oh, hey!\p"
    .string "We don't like disgraceful children\n"
    .string "like you in here!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Oh!\n"
    .string "You!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Our LEADER ERIKA might be quiet,\n"
    .string "but she's famous around here.\p"
	.string "Almost as famous as he was.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Pleased to meet you.\n"
    .string "My hobby is POKéMON training.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Oh!\n"
    .string "Splendid!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "I have a blind date coming up.\n"
    .string "I have to learn to be polite,\l"
    .string "and you are target practice.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Welcome to CELADON GYM!\p"
    .string "You'd better not underestimate\n"
    .string "the sad ladies here.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Oh!\n"
    .string "Beaten!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "I didn't bring my best POKéMON.\n"
    .string "Wait until next time, you\l"
	.string "disgraceful little copy!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED, {PLAYER}$"

