SSAnne_1F_Room2_Text_TylerIntro::
    .string "I love POKéMON!\n"
    .string "Do you? Did he?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Wow! \n"
    .string "Decent battling!!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Listen, listen!\n"
    .string "Let me be your friend, okay?\p"
    .string "Oh… Nevermind.\n"
    .string "I thought you were someone else.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "I collected these POKéMON\n"
    .string "from all around the world!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Oh, no!\n"
    .string "I went around the world for these!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "You hurt my poor POKéMON!\p"
    .string "I demand that you heal them at a\n"
    .string "POKéMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "We are cruising around the world,\n"
    .string "my children and I. Just like he did.$"

