Route15_Text_KindraIntro::
    .string "I just got some POKéMON.\n"
    .string "Can you check them out?$"

Route15_Text_KindraDefeat::
    .string "You're not good enough!$"

Route15_Text_KindraPostBattle::
    .string "He was an expert on POKéMON.\n"
    .string "Better at it than PROFESSOR OAK was.\p"
    .string "You? You are just a little kid who\n"
    .string "knows nothing about this world.$"

Route15_Text_BeckyIntro::
    .string "You look familiar, so I think we\n"
    .string "should battle. It'd be an honor.\p"
    .string "I'll give it a go!$"

Route15_Text_BeckyDefeat::
    .string "No, wrong! You're not him.$"

Route15_Text_BeckyPostBattle::
    .string "I'm afraid of you. You look so\n"
    .string "ugly and mean!$"

Route15_Text_EdwinIntro::
    .string "When I whistle, I can summon bird\n"
    .string "POKéMON to wipe out kids like you.$"

Route15_Text_EdwinDefeat::
    .string "Ow!\n"
    .string "That's tragic!$"

Route15_Text_EdwinPostBattle::
    .string "You're not cut out for battles.\n"
    .string "You're just a wannabe kid.$"

Route15_Text_ChesterIntro::
    .string "Hmm? My birds are shivering!\n"
    .string "You're evil, aren't you?$"

Route15_Text_ChesterDefeat::
    .string "Just as I thought!$"

Route15_Text_ChesterPostBattle::
    .string "This is so obvious, you should know\n"
    .string "this, but…\p"
    .string "Copying his journey down to the\n"
    .string "smallest detail is wrong. $"

Route15_Text_GraceIntro::
    .string "Oh, you're a little cutie!\n"
    .string "Want to sign my autograph?$"

Route15_Text_GraceDefeat::
    .string "You looked like him, too!$"

Route15_Text_GracePostBattle::
    .string "I don't forgive you.\n"
    .string "Why are you pranking us\l"
    .string "in KANTO when he's gone?$"

Route15_Text_OliviaIntro::
    .string "I raise POKéMON for protection\n"
    .string "because I live alone. Like he did.$"

Route15_Text_OliviaDefeat::
    .string "POKéMON isn't about winning or\n"
    .string "losing for me.\p"
	.string "We already lost him. It's sad,\n"
	.string "but we have to keep pushing on.$"

Route15_Text_OliviaPostBattle::
    .string "I love having my POKéMON greet me\n"
    .string "when I get home.\p"
    .string "It's so reassuring.\n"
	.string "Despite our loss.$"

Route15_Text_ErnestIntro::
    .string "Hey, wannabe! C'mon!\n"
    .string "I just got these off another loser!$"

Route15_Text_ErnestDefeat::
    .string "Why not?$"

Route15_Text_ErnestPostBattle::
    .string "Life's too short.\n"
    .string "It's cool to live as an outlaw.\l"
    .string "TEAM ROCKET RULES!\p"
	.string "If he was a ROCKET, at least he'd\n"
	.string "die happily.\l"
	.string "Or maybe he'd still be here with us.$"

Route15_Text_AlexIntro::
    .string "Fork over all your cash when you\n"
    .string "lose to me!$"

Route15_Text_AlexDefeat::
    .string "That can't be true!$"

Route15_Text_AlexPostBattle::
    .string "I was just joking about the money.\n"
    .string "Don't take me all serious.$"

Route15_Text_CeliaIntro::
    .string "What's sad and happening?\n"
    .string "Our loss! Quit mocking it!$"

Route15_Text_CeliaDefeat::
    .string "I said quit!$"

Route15_Text_CeliaPostBattle::
    .string "I grieve about his disappearance\n"
    .string "a lot of the time.$"

Route15_Text_YazminIntro::
    .string "Want to play with my POKéMON?\n"
	.string "He wiped the floor with mine.\p"
	.string "I should train on weak people\n"
	.string "like you.$"

Route15_Text_YazminDefeat::
    .string "I was too impatient!$"

Route15_Text_YazminPostBattle::
    .string "I can't believe I was beaten by\n"
	.string "a wannabe kid! Get out of my sight!$"

Route15_Text_RouteSign::
    .string "ROUTE 15\n"
    .string "West to FUCHSIA CITY$"

Route15_Text_MyaIntro::
    .string "MYA: You're perfect.\n"
    .string "Help me train my little brother?$"

Route15_Text_MyaDefeat::
    .string "MYA: RON, wait, I realized!\n"
    .string "The kid isn't who we thought he was!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Quit deceiving us.\n"
    .string "You will never be him.$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Do you want to challenge us?\n"
    .string "You'll need some originality, though.$"

Route15_Text_RonIntro::
    .string "RON: Look, look, it's him!\n"
    .string "It's him!$"

Route15_Text_RonDefeat::
    .string "RON: Oh, no, no…\n"
    .string "Sis, I'm sorry!\p"
	.string "I thought it was really him!$"

Route15_Text_RonPostBattle::
    .string "RON: Oh, bleah…\n"
    .string "I wish I had a nice sibling\l"
	.string "like him…$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Did you want to battle with\n"
    .string "my sister and me?\p"
    .string "You need originality, then.$"
