Route16_Text_LaoIntro::
    .string "What do you want?$"

Route16_Text_LaoDefeat::
    .string "Don't you dare laugh at us!$"

Route16_Text_LaoPostBattle::
    .string "We just want our hero back.\n"
    .string "What's it to you?$"

Route16_Text_KojiIntro::
    .string "Nice BIKE!\n"
    .string "Hand it over!$"

Route16_Text_KojiDefeat::
    .string "Knockout!$"

Route16_Text_KojiPostBattle::
    .string "Forget it, who needs your BIKE!$"

Route16_Text_LukeIntro::
    .string "Come out and play, little copy!$"

Route16_Text_LukeDefeat::
    .string "You little wannabe!$"

Route16_Text_LukePostBattle::
    .string "I hate copycats!\n"
    .string "Get out of my face!$"

Route16_Text_HideoIntro::
    .string "Hey, you just bumped me!$"

Route16_Text_HideoDefeat::
    .string "Kaboom!$"

Route16_Text_HideoPostBattle::
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to VERMILION from\n"
    .string "FUCHSIA going along the coast.$"

Route16_Text_CamronIntro::
    .string "I'm feeling angry due to our loss!\n"
    .string "I need a punching bag to cope!$"

Route16_Text_CamronDefeat::
    .string "Bad, bad, bad!$"

Route16_Text_CamronPostBattle::
    .string "If I'm going to have POKéMON, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave people like you\n"
    .string "in tatters.$"

Route16_Text_RubenIntro::
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"

Route16_Text_RubenDefeat::
    .string "Don't make me mad!\n"
	.string "Stop wearing his face!$"

Route16_Text_RubenPostBattle::
    .string "I get my kicks by harassing people\n"
    .string "with my stinking POKéMON.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.\p"
	.string "It really helps me forget thinking\n"
	.string "about his disappearance. ..Sniff..$"

Route16_Text_MonSprawledOutInSlumber::
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Route16_Text_CyclingRoadSign::
    .string "Enjoy the slope!\n"
    .string "CYCLING ROAD$"

Route16_Text_RouteSign::
    .string "ROUTE 16\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route16_Text_JedIntro::
    .string "JED: Our love for him knows no bounds.\n"
    .string "We appreciate him and we show it!$"

Route16_Text_JedDefeat::
    .string "JED: Oh, no!\n"
    .string "He has seen me as a loser!$"

Route16_Text_JedPostBattle::
    .string "JED: Listen, LEA.\n"
    .string "He's not who we thought he was.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: You wear his face?\n"
    .string "Is there no love in your heart?$"

Route16_Text_LeaIntro::
    .string "LEA: Sometimes, the intensity of\n"
    .string "our love for him scares me.$"

Route16_Text_LeaDefeat::
    .string "LEA: Ohh! But he looks cool\n"
    .string "even when we lose!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ehehe, I'm sorry.\n"
    .string "I thought you were really him.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Doesn't it feel lonely for\n"
    .string "you or your POKéMON? GOOD!!$"
