Route6_Text_RickyIntro::
    .string "Who's there?\n"
    .string "Quit listening in on us!$"

Route6_Text_RickyDefeat::
    .string "I just can't win!$"

Route6_Text_RickyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_NancyIntro::
    .string "Excuse me!\n"
    .string "This is a private conversation!$"

Route6_Text_NancyDefeat::
    .string "Ugh!\n"
    .string "I hate losing.$"

Route6_Text_NancyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_KeigoIntro::
    .string "There aren't many bugs out here.\n"
	.string "I want MISSINGNO back.\p"
	.string "Did you kill it?$"

Route6_Text_KeigoDefeat::
    .string "No!\n"
    .string "You're kidding!$"

Route6_Text_KeigoPostBattle::
    .string "I like bugs, so I want him back.$"

Route6_Text_JeffIntro::
    .string "HALT!\n"
    .string "You shall not pass!$"

Route6_Text_JeffDefeat::
    .string "This stinks…\n"
    .string "I couldn't stop you…$"

Route6_Text_JeffPostBattle::
    .string "I should bring more POKéMON with\n"
    .string "me. I'll then stop you that way.$"

Route6_Text_IsabelleIntro::
    .string "Me?\n"
    .string "Well, okay. I'll play!$"

Route6_Text_IsabelleDefeat::
    .string "Things just didn't work…$"

Route6_Text_IsabellePostBattle::
    .string "I want to get stronger.\n"
    .string "What was his secret?$"

Route6_Text_ElijahIntro::
    .string "I've always seen you around.\n"
    .string "We should rematch!$"

Route6_Text_ElijahDefeat::
    .string "You're too good!$"

Route6_Text_ElijahPostBattle::
    .string "It's not him.\p"
	.string "Were his POKéMON weak?\n"
    .string "Or, are you just evil?$"

Route6_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"

