Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "Glad I am seeing you again!$"

Route3_Text_ColtonDefeat::
    .string "Congratulations! You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "Oh wait. You aren't him.\n"
    .string "Why are you so mean?$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "He would have still been here\n"
    .string "with us had he brought a spare\l"
    .string "pair of shorts.$"

Route3_Text_JaniceIntro::
    .string "You looked at me, didn't you?\n"
    .string "I always wanted to battle with him.$"

Route3_Text_JaniceDefeat::
    .string "Yay! It was an honor.$"

Route3_Text_JanicePostBattle::
    .string "…I paid you, and you aren't him.\n"
    .string "GET OUT OF MY SIGHT, YOU\l"
	.string "GODDAMN SCAMMER BASTARD!$"

Route3_Text_GregIntro::
    .string "Are you him?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat::
    .string "If I had new POKéMON, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "Eurrgh… I'm too lazy\n"
    .string "to head back to the\l"
	.string "POKéMON CENTER…$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Can you sign my autograph?$"

Route3_Text_SallyPostBattle::
    .string "What do you mean you aren't him?\n"
    .string "I WANT MY AUTOGRAPH RIGHT NOW!!!$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "He wasn't wearing any either.$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "He should have always worn\n"
    .string "shorts, even in winter.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Well, uh, it was nice\n"
    .string "to meet you.$"

Route3_Text_RobinIntro::
    .string "Did my senpai touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it? Just a cosplayer?$"

Route3_Text_RobinPostBattle::
    .string "I want my money back.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"

