Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\n"
	.string "You're off to the POKéMON LEAGUE?\p"
	.string "Forget about it!\n"
	.string "You will never be as great as RED\l"
	.string "was. I will stomp you out like a bug.$"

Route22_Text_EarlyRivalDefeat::
	.string "…\n"
	.string "We'll still stop you.\p"
	.string "This is our world, his world,\n"
	.string "not yours.$"

Route22_Text_EarlyRivalPostBattle::
	.string "We shaped this world.\n"
	.string "We shaped this story.\p"
	.string "And he's the HERO.\n"
	.string "Who are you?\l"
	.string "You're just a nobody.$"
	
@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: {PLAYER}.\n"
	.string "So you're going to the POKéMON\l"
	.string "LEAGUE? Not on my watch.\p"
	.string "I'll stop you, {PLAYER}, from\n"
	.string "stealing his story!$"

Route22_Text_LateRivalDefeat::
	.string "What!?\p"
	.string "I was just careless, you!$"

Route22_Text_LateRivalPostBattle::
	.string "Listen to me.\n"
	.string "I'm going to the LEAGUE.\p"
	.string "I will defeat the ELITE FOUR.\n"
	.string "I will defeat the CHAMPION.\p"
	.string "And then I will defeat you.$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"

