SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENT: Oh, dear boy!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "Oh, it wasn't you.\n"
    .string "It was him.\l"
    .string "Please give this to him.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENT: Oh, dear girl!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "Oh, it wasn't you.\n"
    .string "It was him.\l"
    .string "Please give this to him.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} obtained a MASTER BALL\n"
    .string "from the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's our secret prototype MASTER\n"
    .string "BALL 2.0.\p"
    .string "It will catch any POKéMON without\n"
    .string "fail!\p"
    .string "You can't use it, though.\n"
    .string "It's not meant for you.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARY: Thank you for helping\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down in KANTO,\n"
    .string "are indebted to you.\p"
	.string "Wait, you aren't him.\n"
	.string "Nevermind.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}!\n"
    .string "So we meet again!\p"
    .string "The PRESIDENT and I are discussing\n"
    .string "a vital expedition project.\p"
    .string "Keep your nose out of our\n"
    .string "world…\p"
    .string "Or, experience a world of pain!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "I lost again. Just as I expected.$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "It's almost cute how you think\n"
    .string "this will accomplish anything.\p"
    .string "Don't you realize that we have\n"
    .string "already lost?\p"
    .string "TEAM ROCKET never wins. He does.\p"
    .string "And you're not him.$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stop right there!\n"
    .string "Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "So, you want to be him?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gaah!\n"
    .string "Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough.\p"
	.string "The boy was his most worthy opponent.$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "The monitor has a snowy mountain on it!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "6F$"

