PokemonMansion_Text_PressSecretSwitch::
    .string "A secret switch!\p"
    .string "Press it?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Who wouldn't?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Not quite yet!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "Halt!\n"
    .string "Don't stop me from looting this\l"
	.string "old cave! The ITEMs are mine!$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Oh, no!\n"
    .string "My bag of loot!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "This place is not for unattended\n"
    .string "kids! Now shoo!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Diary: July 5\n"
    .string "Guyana, South America\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"

