CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah!\p"
    .string "I am BLAINE, the red-hot LEADER\n"
    .string "of CINNABAR GYM!\p"
    .string "My fiery POKéMON are all rough\n"
    .string "and ready with intense heat!\p"
    .string "They incinerate all challengers!\p"
    .string "Hah!\n"
    .string "You better have BURN HEAL!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "I have burned down to nothing!\n"
    .string "Not even ashes remain!\p"
    .string "You have earned the VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "FIRE BLAST is the ultimate fire\n"
    .string "technique.\p"
    .string "Don't waste it on WATER POKéMON.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah!\p"
    .string "The VOLCANOBADGE heightens the\n"
    .string "SPECIAL stats of your POKéMON.\p"
    .string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} received TM38\n"
    .string "from BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 contains FIRE BLAST.\n"
    .string "Teach it to FIRE-type POKéMON.\p"
    .string "VULPIX or CHARMELEON would be\n"
    .string "ideal for that move.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Do you know how hot POKéMON fire\n"
    .string "breath can get?\p"
	.string "Just hot enough to roast FAKEs\n"
	.string "like you!$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "I was an identity thief, but I went\n"
    .string "straight as an GYM WORKER.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's identity.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "I've studied POKéMON thoroughly.\n"
    .string "You can't win! The only one who\l"
	.string "even stood a chance was him!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Waah!\n"
    .string "You're too good at copying!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "Our loss is too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "I like using FIRE-type POKéMON.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "I wish there were a thief POKéMON.\n"
    .string "I'd use that!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "I know why BLAINE became a\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Our LEADER, BLAINE, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "POKéMON appeared.\p"
    .string "Its light allowed BLAINE to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "I've been to many GYMS, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, FLAREON, CHARIZARD…\n"
    .string "Those are popular FIRE POKéMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Fire is weak against H2O.\n"
	.string "He was smart, so he knew that.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the FIRE\n"
    .string "type beats ICE-type POKéMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Liar in the making!\p"
    .string "The hotheaded BLAINE is a FIRE\n"
    .string "POKéMON pro.\p"
    .string "Douse his spirits with water!\p"
    .string "You'd better take some\n"
    .string "BURN HEALS, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, RED, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "POKéMON Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a TRAINER!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "Are you a liar?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "Is this story yours?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "Do you belong here?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Should you keep playing?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "Are you a FAKE?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "Are you RED?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "That's right!\p"
    .string "You will never be him, but\n"
	.string "good luck trying! Haha!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Sorry!\n"
    .string "Bad call!$"

