CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "I came to visit the CINNABAR TUNNEL,\n"
    .string "but got too tired.\p"
    .string "The CINNABAR GYM's now located\n"
    .string "there, they say.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "You don't have friends, do you?$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKéMON can still learn techniques\n"
    .string "after canceling evolution.\p"
    .string "Evolution can wait until new moves\n"
    .string "have been learned.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Hey, you kept me waiting!\n"
    .string "Ready to set sail to ONE ISLAND?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Oh, you're still not done yet?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Well, that's it.\n"
    .string "Let's go!$"
