PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: …{PLAYER}.\n"
    .string "What brings you here?\l"
    .string "Is your POKéMON dead?\p"
    .string "LUCKY FOR YOU.\p"
    .string "You don't even know where he is!\n"
    .string "You don't know this story!\l"
	.string "You didn't earn it! Get out!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "What? How could you?\n"
    .string "I didn't take it hard enough on you!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "……Everyone thinks he's dead.\n"
    .string "He isn't.\p"
    .string "He's coming home.\n"
    .string "He has to.$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Even we could not identify the\n"
    .string "wayward ghosts.\p"
    .string "The SILPH SCOPE is able to\n"
    .string "unmask them. But GIOVANNI stole it\l"
	.string "yet again. When will he quit?$"

