SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Bonjour!\n"
    .string "I am le waiter on this ship!\p"
    .string "I don't want to serve you\n"
    .string "… Quitte s'il te plait.$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "The passengers are restless from\n"
    .string "this long voyage.\p"
    .string "You might be challenged by the\n"
    .string "more bored ones!$"

