SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "You look tired.\n"
    .string "You should take a quick nap.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Please give up.$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Sorry, but he did it first.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Your POKéMON seem to adore you,\n"
    .string "kid!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Ghaaah! Not as much as if you were\n"
	.string "him, though!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "If I had started as a TRAINER at\n"
    .string "your age, like him…$"

SilphCo_9F_Text_EdIntro::
    .string "Your POKéMON have weak points!\n"
    .string "His didn't! But, I can nail yours!$"

SilphCo_9F_Text_EdDefeat::
    .string "You hammered me!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Exploiting weak spots does work.\n"
    .string "He did so, at times.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Warg!\n"
    .string "Brothers, I lost!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "My brothers will avenge me!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "9F$"

