Route25_Text_JoeyIntro::
    .string "Local TRAINERS come here to\n"
    .string "practice. He did too.$"

Route25_Text_JoeyDefeat::
    .string "You're decent.$"

Route25_Text_JoeyPostBattle::
    .string "Even the strongest POKéMON\n"
    .string "have weaknesses.\p"
    .string "That's why it's best to raise\n"
    .string "POKéMON of different types.\p"
	.string "That's why he was such a\n"
	.string "great trainer.$"

Route25_Text_DanIntro::
    .string "Dad took me to a great party on\n"
    .string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat::
    .string "I'm not mad!$"

Route25_Text_DanPostBattle::
    .string "On the S.S. ANNE, I saw TRAINERS\n"
    .string "from around the world.\p"
	.string "I wish I could've seen him though…$"

Route25_Text_FlintIntro::
    .string "Stop trying to repeat his\n"
    .string "story! It is disrespectful!$"

Route25_Text_FlintDefeat::
    .string "Aww, darn…$"

Route25_Text_FlintPostBattle::
    .string "I'm still sad about his\n"
    .string "disappearance. At least my\l"
	.string "girlfriend will cheer me up a bit.$"

Route25_Text_KelseyIntro::
    .string "Hi!\n"
    .string "What a nice cosplay!$"

Route25_Text_KelseyDefeat::
    .string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle::
    .string "I wish my boyfriend was as good\n"
    .string "as that kid was.$"

Route25_Text_ChadIntro::
    .string "I had this feeling…\n"
    .string "I knew I had to battle you!$"

Route25_Text_ChadDefeat::
    .string "I knew I'd lose, too!$"

Route25_Text_ChadPostBattle::
    .string "I can't believe I got to battle\n"
	.string "him! Wait, what if it was a scam?$"

Route25_Text_HaleyIntro::
    .string "You had many cute POKéMON.\n"
    .string "I WANT THEM ALL!!$"

Route25_Text_HaleyDefeat::
    .string "Okay, I'll think of something\n"
	.string "else.$"

Route25_Text_HaleyPostBattle::
    .string "You came from MT. SILVER?\n"
    .string "May I have your MEWTWO?$"

Route25_Text_FranklinIntro::
    .string "Give me the REPELs now,\n"
	.string "you disgraceful copycat!$"

Route25_Text_FranklinDefeat::
    .string "You've worked hard.\n"
	.string "...No, you didn't. Ha!$"

Route25_Text_FranklinPostBattle::
    .string "A ZUBAT bit me back in that cave.\n"
    .string "I need the REPELs. Shoo!$"

Route25_Text_NobIntro::
    .string "I'm off to see BILL's\n"
    .string "collection at the cape.$"

Route25_Text_NobDefeat::
    .string "You done got me, and real good,\n"
    .string "too!$"

Route25_Text_NobPostBattle::
    .string "BILL's collection includes many rare\n"
    .string "species of POKéMON. Just like a\l"
	.string "certain young boy's collection did.$"

Route25_Text_WayneIntro::
    .string "You're going to see BILL?\n"
    .string "First, we battle!$"

Route25_Text_WayneDefeat::
    .string "You're something.$"

Route25_Text_WaynePostBattle::
    .string "The trail below is a shortcut to\n"
    .string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
    .string "SEA COTTAGE\n"
    .string "He helped BILL there.$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "This cape is a famous date spot.\p"
    .string "MISTY, the GYM LEADER, has high\n"
    .string "hopes about this place.$"

Route25_Text_AreYouHereAlone::
    .string "Hello, are you here alone?\p"
    .string "If you're out at CERULEAN's cape…\n"
    .string "Well, it should be as a couple.$"

