PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Huh?\n"
    .string "Who are you?\p"
    .string "You aren't RED.\n"
    .string "I don't have my POKéMON anymore, \l"
    .string "so, I am coming to get mine.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Gramps!\n"
    .string "I'm fed up with waiting!\l"
    .string "I need another POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: You have his face…\n"
    .string "Why do you have the same face?\p"
    .string "Who are you?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: This is not your story.\n"
    .string "Go away. He's coming back soon,\l"
    .string "and he'll need it.$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: I'll take this one, then!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: My POKéMON has an\n"
    .string "advantage over yours.\l"
    .string "Just what I need against people\l"
    .string "like you!$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Wait, {PLAYER}!\n"
    .string "You are not going anywhere!\l"
    .string "I'll make sure of that!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "N…no…\n"
    .string "This isn't right.\l"
    .string "You aren't RED.\l"
    .string "RED always wins this battle, not you.$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Yeah!\p"
    .string "RED would have won, but you can't,\n"
    .string "because you're just a poser. Haha!\l"
    .string "I hope you don't succeed!$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: …I need to fix this.\n"
    .string "Get out of my world.$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Gramps!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: …All I want is my rival…\n"
    .string "my friend… back.\l"
    .string "Come home.$"


PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: All right, Gramps!\n"
    .string "Leave it all to me!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "I'll be the hero of this story.\n"
    .string "You shouldn't even be here.$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: {RIVAL}?\n"
    .string "Let me think…\p"
    .string "Oh, that's right, I told you to\n"
    .string "come! Just wait!\p"
    .string "Here, {PLAYER}.\p"
    .string "There are three POKéMON here.\p"
    .string "Haha!\p"
    .string "The POKéMON are held inside\n"
    .string "these POKé BALLS.\p"
    .string "When I was young, I was a serious\n"
    .string "POKéMON TRAINER.\p"
    .string "But now, in my old age, I have\n"
    .string "only these three left.\p"
    .string "You can have one.\n"
    .string "Go on, choose!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: {RIVAL}! Don't be mean to new\n"
	.string "trainers! Be professional.$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Now, {PLAYER}.\p"
    .string "Inside those three POKé BALLS are\n"
    .string "POKéMON.\p"
    .string "Which one will you choose for\n"
    .string "yourself?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: Hey!\n"
    .string "Don't go away yet!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! CHARMANDER is your choice.\n"
    .string "You should raise it patiently.\p"
    .string "So, {PLAYER}, you're claiming the\n"
    .string "FIRE POKéMON CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SQUIRTLE is your choice.\n"
    .string "It's one worth raising.\p"
    .string "So, {PLAYER}, you've decided on the\n"
    .string "WATER POKéMON SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "I see! BULBASAUR is your choice.\n"
    .string "It's very easy to raise.\p"
    .string "So, {PLAYER}, you want to go with\n"
    .string "the GRASS POKéMON BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "This POKéMON is really quite\n"
    .string "energetic!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: If a wild POKéMON appears,\n"
    .string "your POKéMON can battle it.\p"
    .string "With it at your side, you should be\n"
    .string "able to reach the next town.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: {PLAYER}, raise your young\n"
    .string "POKéMON by making it battle.\p"
    .string "It has to battle for it to grow.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Oh, {PLAYER}!\n"
    .string "How is my old POKéMON?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a POKéMON\n"
    .string "TRAINER.\p"
    .string "What's that?\n"
    .string "You have something for me?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} delivered OAK'S PARCEL.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah! \n"
    .string "It's yet another custom POKé BALL\l"
    .string "that I had on order.\n"
    .string "Thank you!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Oh, right!\n"
    .string "I have a request for you, FIRE.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "On the desk there is a POKéDEX!\p"
    .string "It automatically records data on\n"
    .string "POKéMON you've seen or caught.$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} and {RIVAL}.\n"
    .string "Take these with you.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} received the POKéDEX\n"
    .string "from PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: You can't get detailed data\n"
    .string "on POKéMON by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild POKéMON.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} received five POKé BALLS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "BLUE lost his POKéDEX, so I am\n"
    .string "giving him another one.\l"
    .string "Please don't lose it again, OK?$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "To make a complete guide on all\n"
    .string "the POKéMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON around the world wait for\n"
    .string "you, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Those are POKé BALLS.\n"
    .string "They contain POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "That's PROF. OAK's last POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "I'm sorry.\n"
    .string "We couldn't find him.\l"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "I study POKéMON as PROF. OAK's\n"
    .string "AIDE.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "OAK's POKéMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. OAK may not look like much,\n"
    .string "but he's the authority on POKéMON.\p"
    .string "Many POKéMON TRAINERS hold him in\n"
    .string "high regard.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s POKéDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

