Route9_Text_AliciaIntro::
    .string "My SENPAI is walking past!\n"
    .string "You're mine!$"

Route9_Text_AliciaDefeat::
    .string "You deceived me…$"

Route9_Text_AliciaPostBattle::
    .string "Give me back my money.\n"
    .string "Stop pretending to be him.$"

Route9_Text_ChrisIntro::
    .string "Who's that walking there with those\n"
    .string "good-looking POKéMON?$"

Route9_Text_ChrisDefeat::
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle::
    .string "Keep walking!$"

Route9_Text_DrewIntro::
    .string "I'm taking the ROCK TUNNEL to\n"
    .string "go to LAVENDER…$"

Route9_Text_DrewDefeat::
    .string "You can't measure up to him…$"

Route9_Text_DrewPostBattle::
    .string "Are you off to ROCK TUNNEL, too?$"

Route9_Text_CaitlinIntro::
    .string "Don't you dare patronize us!$"

Route9_Text_CaitlinDefeat::
    .string "No!\n"
    .string "You're too much like him!$"

Route9_Text_CaitlinPostBattle::
    .string "You're obviously a copy.\n"
    .string "Please do something of your own.$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "You're not who I thought you were.$"

Route9_Text_JeremyPostBattle::
    .string "You sure have guts standing up to\n"
    .string "us all here.$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Aren't you a little worm?!$"

Route9_Text_BriceDefeat::
    .string "What's that?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Kids should be tough!\l"
	.string "Like he was!$"

Route9_Text_BrentIntro::
    .string "I got up early every day to raise\n"
    .string "my POKéMON from cocoons!$"

Route9_Text_BrentDefeat::
    .string "WHAT?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
    .string "I am yet to still collect more\n"
    .string "than bugs to get stronger…\l"
	.string "It didn't work against him either.$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha! Wait!\n"
    .string "You're not him!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!\l"
	.string "Even when he's gone!$"

Route9_Text_ConnerIntro::
    .string "Go, my super BUG POKéMON!$"

Route9_Text_ConnerDefeat::
    .string "My bugs…$"

Route9_Text_ConnerPostBattle::
    .string "If you don't like BUG POKéMON,\n"
    .string "you bug me!$"

Route9_Text_RouteSign::
    .string "ROUTE 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"

