Route11_Text_HugoIntro::
    .string "Win, lose, or draw!$"

Route11_Text_HugoDefeat::
    .string "Atcha!\n"
    .string "Didn't go my way!$"

Route11_Text_HugoPostBattle::
    .string "POKéMON is life!\n"
    .string "And to live is to play games!$"

Route11_Text_JasperIntro::
    .string "Competition!\n"
    .string "I can't get enough!$"

Route11_Text_JasperDefeat::
    .string "I had a chance!$"

Route11_Text_JasperPostBattle::
    .string "You can't be a coward in the world\n"
    .string "of POKéMON!$"

Route11_Text_EddieIntro::
    .string "Let's go, but don't cheat!\n"
	.string "I've always wanted to take on him!$"

Route11_Text_EddieDefeat::
    .string "Huh?\n"
    .string "That's not right!\l"
	.string "You aren't him!$"

Route11_Text_EddiePostBattle::
    .string "I have regrets.\n"
	.string "Give me back my money.\l"
	.string "This is a scam!!$"

Route11_Text_BraxtonIntro::
    .string "Careful!\n"
    .string "I'm still laying down cables!$"

Route11_Text_BraxtonDefeat::
    .string "That was electric!$"

Route11_Text_BraxtonPostBattle::
    .string "Spread the word to save energy!\n"
	.string "He didn't.$"

Route11_Text_DillonIntro::
    .string "I just became a TRAINER.\n"
    .string "But, I think I can win.$"

Route11_Text_DillonDefeat::
    .string "My POKéMON couldn't win…\n"
    .string "Haven't they grown enough?$"

Route11_Text_DillonPostBattle::
    .string "Please leave me alone.$"

Route11_Text_DirkIntro::
    .string "Fwahaha!\n"
    .string "I've only lost to him!\l"
	.string "I wipe the floor with kids like you!$"

Route11_Text_DirkDefeat::
    .string "My second loss!$"

Route11_Text_DirkPostBattle::
    .string "You were just lucky. Now leave.$"

Route11_Text_DarianIntro::
    .string "I have never won…\n"
	.string "He was too strong…$"

Route11_Text_DarianDefeat::
    .string "I saw this coming… We all did.$"

Route11_Text_DarianPostBattle::
    .string "The GAME doesn't let me be lucky…$"

Route11_Text_YasuIntro::
    .string "I'm the best in my class.\n"
    .string "I train every morning.\l"
	.string "But not as good as he was.$"

Route11_Text_YasuDefeat::
    .string "Damn!\n"
    .string "My POKéMON need to be stronger!$"

Route11_Text_YasuPostBattle::
    .string "SNORLAX came down from the mountains.\n"
    .string "I bet it'd be strong if you can\l"
    .string "catch it.$"

Route11_Text_BernieIntro::
    .string "Watch out for live wires!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "What's with you kids?$"

Route11_Text_BerniePostBattle::
    .string "Back to work! Leave now!$"

Route11_Text_DaveIntro::
    .string "I raised my POKéMON carefully.\n"
    .string "They should be ready by now!$"

Route11_Text_DaveDefeat::
    .string "Goodbye.$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "I better go find stronger ones.$"

Route11_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"

