CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe! The slots have been reeling\n"
    .string "in the dough big-time ever since he\l"
    .string "disappeared!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "CHIEF!\p"
    .string "We just shipped two thousand\n"
    .string "more POKéMON as slot prizes\l"
    .string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Don't touch the poster at the GAME\n"
    .string "CORNER! You'd just copy him!\p"
    .string "Quit and do something of your own.$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
