Route14_Text_CarterIntro::
    .string "You need to use TMs to teach good\n"
    .string "moves to POKéMON. He did so.$"

Route14_Text_CarterDefeat::
    .string "You're not good enough.$"

Route14_Text_CarterPostBattle::
    .string "You have some HMs, right? POKéMON\n"
    .string "can't forget those moves easily.$"

Route14_Text_MitchIntro::
    .string "My bird POKéMON should be ready\n"
    .string "to wipe the floor with kids like you.$"

Route14_Text_MitchDefeat::
    .string "How come you're just like him?$"

Route14_Text_MitchPostBattle::
    .string "Tell me your secrets!\n"
    .string "How do you manage to be like him\l"
	.string "in absolutely every way?$"

Route14_Text_BeckIntro::
    .string "They have TMs on sale at the\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"

Route14_Text_BeckDefeat::
    .string "Aww, bummer!$"

Route14_Text_BeckPostBattle::
    .string "Try teaching POKéMON a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"

Route14_Text_MarlonIntro::
    .string "You'll should soar with CHARIZARD\n"
    .string "into the sky!\p"
	.string "Maybe you'll even head to the\n"
	.string "mountains and meet him.$"

Route14_Text_MarlonDefeat::
    .string "Shot down in flames!$"

Route14_Text_MarlonPostBattle::
    .string "POKéMON like his are my one true love.\n"
    .string "But I can only catch birds for now.$"

Route14_Text_DonaldIntro::
    .string "Have you heard the legend of the\n"
    .string "trainer from PALLET?$"

Route14_Text_DonaldDefeat::
    .string "Why?\n"
    .string "Why'd I lose? You're not him!$"

Route14_Text_DonaldPostBattle::
    .string "Well, the trainer from PALLET was our\n"
    .string "PRIDE and CHAMPION.\p"
    .string "Then he went to a mountain one day and\n"
    .string "vanished. Please quit mocking this.\l"
	.string "This is not funny.$"

Route14_Text_BennyIntro::
    .string "I'm worried, but okay.\n"
    .string "Let's go!$"

Route14_Text_BennyDefeat::
    .string "I knew it!$"

Route14_Text_BennyPostBattle::
    .string "Winning, losing… It's insignificant\n"
    .string "when even the best will die on a\l"
	.string "snowy mountain.$"

Route14_Text_LukasIntro::
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "You will never be him! Get lost!$"

Route14_Text_LukasPostBattle::
    .string "What, what, what, wannabe?\n"
    .string "What do you want still?$"

Route14_Text_IsaacIntro::
    .string "I need to forget about our loss.\n"
    .string "Shut up and battle.$"

Route14_Text_IsaacDefeat::
    .string "What?\n"
    .string "You wannabe!$"

Route14_Text_IsaacPostBattle::
    .string "Raising POKéMON is a drag, man.\p"
	.string "Almost as if this is all a game\n"
	.string "where we all lose in the end.$"

Route14_Text_GeraldIntro::
    .string "We ride out here because they\n"
    .string "put us here.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle::
    .string "It's uncool that you made your\n"
    .string "entire identity to just copy his.\p"
    .string "Disrespecting his honor is wrong!\n"
    .string "And you know it!$"

Route14_Text_MalikIntro::
    .string "POKéMON battle?\n"
    .string "Cool! Rumble!$"

Route14_Text_MalikDefeat::
    .string "Blown away!$"

Route14_Text_MalikPostBattle::
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"

Route14_Text_RouteSign::
    .string "ROUTE 14\n"
    .string "West to FUCHSIA CITY$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, he's back, he's back!\n"
    .string "Let's try to attract his attention.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Whimper…\n"
    .string "You aren't him, are you?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Please get out of our sight.$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: We can battle if you have\n"
    .string "two POKéMON.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, here we go!\n"
    .string "He's back!\p"
	.string "Please come back to PALLET!\n"
	.string "Everyone misses you!$"
	
Route14_Text_JanDefeat::
    .string "JAN: Eeeeh!\n"
    .string "What kind of sick joke is this?$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, don't cry!\n"
    .string "That guy was just a meanie.\l"
	.string "..You, stop making fun of our loss!$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: You want to battle?\n"
    .string "You don't have enough POKéMON.$"
