SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "This ship, she is a luxury liner for\n"
    .string "TRAINERS of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited TRAINERS.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "What are you doing here?\n"
    .string "Why don't you just quit?\p"
    .string "I told you, this is RED's story,\n"
    .string "it was never meant for you!$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "… … … … … … … …\n"
    .string "… … Oh god.\l"
    .string "What have you done?$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: Sniff…\p"
    .string "I have to go mourn because\n"
    .string "of what you just did.\p"
	.string "Are you proud of yourself?$"

