Route10_Text_MarkIntro::
    .string "Wow, look at your costume!\n"
    .string "Maybe you're a POKéMANIAC, too?\l"
    .string "Want to see my cosplay?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle::
    .string "I have more suits at home!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "I found some wacky 'shrooms!\p"
    .string "They help me cope with our loss!\n"
	.string "Haha-ha-choo!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-choo!\n"
    .string "Ha-choo!\l"
    .string "Snort! Snivel!$"

Route10_Text_HermanIntro::
    .string "Hi, kid!\n"
    .string "Want to see my POKéMON?$"

Route10_Text_HermanDefeat::
    .string "Oh, no!\n"
    .string "My POKéMON!$"

Route10_Text_HermanPostBattle::
    .string "I don't like you.\n"
    .string "I don't like anyone better than him!$"

Route10_Text_HeidiIntro::
    .string "I've been out at a POKéMON GYM\n"
    .string "a few times.\l"
    .string "…But I always lose.\p"
	.string "He never lost though.$"

Route10_Text_HeidiDefeat::
    .string "Ohh!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle::
    .string "I noticed some POKéMANIACS\n"
    .string "prowling around.\p"
    .string "Are you one of them?\n"
    .string "Going up here in the mountains?$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "This mountain air is delicious!$"

Route10_Text_TrentDefeat::
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle::
    .string "I feel bloated on mountain air!$"

Route10_Text_CarolIntro::
    .string "I'm feeling a bit faint.\n"
    .string "I haven't hiked in some time.\l"
	.string "I was too busy mourning.$"

Route10_Text_CarolDefeat::
    .string "I'm too tired.\n"
    .string "I wasn't up for it.$"

Route10_Text_CarolPostBattle::
    .string "I wish he was there…\n"
    .string "Come home.$"

Route10_Text_RockTunnelDetourToLavender::
    .string "ROCK TUNNEL\n"
    .string "Detour to LAVENDER TOWN$"

Route10_Text_RockTunnel::
    .string "ROCK TUNNEL$"

Route10_Text_PowerPlant::
    .string "POWER PLANT$"

