LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "That's odd, MR. FUJI isn't here.\n"
    .string "Where'd he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI had been praying alone\n"
    .string "for RATICATE.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "This is really MR. FUJI's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "It's so warm!\n"
    .string "POKéMON are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Stop kidding yourself.\n"
    .string "You're not him.\p"
    .string "I'm giving away this POKé FLUTE,\n"
    .string "so you can at least do something\l"
	.string "for once.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Now go and use it on the SNORLAX\n"
    .string "that block the pathways..$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you? It helped him.$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "POKéMON FAN MAGAZINE\n"
    .string "Top 10 Greatest POKéMON TRAINERs\p"
    .string "The number one is…\p"
    .string "Gone! He was last seen on a mountain.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

