RockTunnel_1F_Text_LennyIntro::
    .string "This tunnel goes a long way, kid!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "Doh!\n"
    .string "You win!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "Watch for POKéMANIACS.\n"
    .string "The more rabid ones can put the\l"
    .string "squeeze on people like you!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm.\n"
    .string "Maybe I'm lost in here…$"

RockTunnel_1F_Text_OliverDefeat::
    .string "Ease up!\n"
    .string "What am I doing?\l"
    .string "Which way is out?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "That sleeping POKéMON on ROUTE 12\n"
    .string "forced me to take this detour.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Outsiders like you need to show us\n"
    .string "some respect!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "Please stop acting like you're him.$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "I hope you get lost here.$"

RockTunnel_1F_Text_AshtonIntro::
    .string "Give me your clothes!\n"
    .string "I've always wanted to cosplay him!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "Aw man!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "Oh well, I hope to save up and\n"
	.string "buy clothing like his!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Eek!\p"
    .string "Don't try anything funny in the\n"
    .string "dark!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "It was too dark…$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "I saw him in a similar tunnel.$"

RockTunnel_1F_Text_DanaIntro::
    .string "I came this far looking for him.$"

RockTunnel_1F_Text_DanaDefeat::
    .string "Oops.$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "You looked like him.\n"
    .string "I always wanted to fight him!\p"
	.string "Too bad though.\n"
	.string "You don't measure up.$"

RockTunnel_1F_Text_ArianaIntro::
    .string "You have his POKéMON!\n"
    .string "Let's start!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "You play hard! Like he did.$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Whew!\n"
    .string "I'm all sweaty now.$"

RockTunnel_1F_Text_RouteSign::
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"

