CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "You aren't him.\n"
    .string "I won't serve to you.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "Sorry, but we do not serve\n"
    .string "disrespectful copies like you.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "TEAM ROCKET has a basement under the\n"
    .string "GAME CORNER. Leave and go there.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Munch…\p"
    .string "The man at that table lost it all\n"
    .string "when he heard the news.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "You look like him.\n"
    .string "But you aren't. Leave.$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} received a COIN CASE\n"
    .string "from the man.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Make room for this!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "I always thought I was going to\n"
    .string "win it back…$"

