Text_OnlyPassWithChampDontHaveYet::
	.string "Only trainers who are proven\n"
	.string "to be worthy are allowed through\l"
	.string "to MT.SILVER.\p"
	.string "You aren't the CHAMPION yet!\n"
	.string "It's too dangerous out there.\p"
	.string "I can't let you pass.$"

Text_OhThatsChampGoRightAheadGoRightAhead::
	.string "Oh! So you are CHAMPION!\n"
	.string "You're worthy of entering\l"
	.string "MT. SILVER!\p"
	.string "Go right ahead.\n"
	.string "Save him for all of us.$"
	