SilphCo_10F_Text_GruntIntro::
    .string "So good of you to join me!$"

SilphCo_10F_Text_GruntDefeat::
    .string "I'm stunned!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "Nice try, but the boardroom is up\n"
    .string "one more floor.$"

SilphCo_10F_Text_TravisIntro::
    .string "Enough of this silly game!$"

SilphCo_10F_Text_TravisDefeat::
    .string "No continues left!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "You are not satisfied with beating\n"
    .string "me. You want to be CHAMPION.\p"
	.string "Please quit playing. You will never be him.$"

SilphCo_10F_Text_WaaaImScared::
    .string "Waaaaa!\n"
    .string "I'm scared!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "About me crying…\n"
    .string "Please keep it a secret.$"

SilphCo_10F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "10F$"

