SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Hi.\n"
    .string "You must like POKéMON.\p"
    .string "{PLAYER}: He liked POKéMON too.\p"
    .string "{PLAYER}: Pardon?\n"
    .string "You think you're original?\p"
    .string "COPYCAT: Haha.\n"
    .string "Get out of my sight.$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Hi.\n"
    .string "You must like POKéMON.\p"
    .string "{PLAYER}: No, not me.\n"
    .string "I asked you.\p"
    .string "{PLAYER}: Pardon?\n"
    .string "You're weird!\p"
    .string "COPYCAT: Hmm? Quit mimicking?\n"
    .string "But that's my favorite hobby!$"

Text_MimicTeach::
    .string "Are you also a COPYCAT?\p"
    .string "You know what?\n"
    .string "I can teach the move MIMIC.$"

Text_MimicDeclined::
    .string "Don't you like MIMIC?$"

Text_MimicWhichMon::
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Isn't copying someone\n"
    .string "else fun?\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what he said and did?$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Isn't copying someone\n"
    .string "else fun?\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what he said and did?$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR LOOK AT ME,\n"
    .string "SEE HOW PRETTY I CAN BE?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "This is a rare POKéMON!\n"
    .string "Huh? It's only a doll!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "A game with MARIO wearing a bucket\n"
    .string "on his head!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\l"
    .string "Favorite POKéMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
