RocketHideout_B3F_Text_GruntIntro::
    .string "BOSS thinks you can revive\n"
    .string "POKéMON with the SILPH SCOPE.$"

RocketHideout_B3F_Text_GruntDefeat::
    .string "Please surrender.$"

RocketHideout_B3F_Text_GruntPostBattle::
    .string "Think you can reach the BOSS?\n"
    .string "You won't. This isn't your story.$"

RocketHideout_B3F_Text_Grunt1Intro::
    .string "Stop meddling in TEAM ROCKET's\n"
    .string "affairs or else!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Oof!\n"
    .string "Taken down!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "SILPH SCOPE?\n"
    .string "It's on top. But you have a snow's\p"
    .string "chance in hell of getting there!$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "We got word from upstairs that you\n"
    .string "were coming!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "What?\n"
    .string "I lost? No!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "Go ahead and quit playing.$"

RocketHideout_4F_Text_Grunt2Intro::
    .string "I know you!\n"
    .string "You ruined our world!$"

RocketHideout_4F_Text_Grunt2Defeat::
    .string "Burned again!$"

RocketHideout_4F_Text_Grunt2PostBattle::
    .string "Do you have something against KANTO?$"

RocketHideout_4F_Text_Grunt3Intro::
    .string "How can you see the beauty of\n"
    .string "our evil? He didn't!$"

RocketHideout_4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_4F_Text_Grunt3PostBattle::
    .string "KANTO!\n"
    .string "I'm sorry we failed your pride!$"

RocketHideout_4F_Text_Grunt1Intro::
    .string "I have the LIFT KEY.\n"
	.string "But you'll not obtain it,\l"
	.string "because you're a nobody.$"

RocketHideout_4F_Text_Grunt1Defeat::
    .string "No!$"

RocketHideout_4F_Text_Grunt1PostBattle::
    .string "Oh, no!\n"
    .string "I dropped the LIFT KEY!$"

