PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER was erected in the\n"
    .string "memory of POKéMON and people\p"
	.string "that died.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "You don't deserve to.\n"
    .string "Not when you wear his face like that.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I miss him.\n"
    .string "I wonder if he belongs here…?$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Why…\n"
    .string "Where did you go?…$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "I am a CHANNELER.\p"
    .string "There are spirits up to mischief.\n"
    .string "I sense them high in the TOWER.$"

