FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "We nicknamed the WARDEN\n"
    .string "“SLOWPOKE.”\p"
    .string "You know, he has that vacant look\n"
    .string "like a SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "WARDEN SLOWPOKE is very\n"
    .string "knowledgeable about POKéMON.\p"
    .string "He even has some fossils of rare,\n"
    .string "extinct POKéMON.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "Hi, regular visitor!\n"
    .string "Have you caught anything new?$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "WARDEN SLOWPOKE is running a\n"
    .string "promotion campaign right now.\p"
    .string "Find the boy on a mountain after\n"
	.string "becoming CHAMPION.\p"
    .string "If you can make it, you'll win a\n"
    .string "very convenient prize.$"

