CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "Are you still here? Still playing?\n"
    .string "You aren't RED. This isn't your story.$"

CeruleanCity_Text_RivalDefeat::
    .string "Get out!\n"
    .string "I don't know what's\l"
    .string "your problem, man!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: You're doing the same\n"
    .string "things he did. All of them.\p"
    .string "The same places. The same POKeMON.\n"
    .string "The same badges. You're just a copy.$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always plodding behind me.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "I thought you had his face before.\n"
    .string "It's similar, but it's not his.\p"
    .string "Now that I look at you,\n"
    .string "you don't look anything like him.$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Stay out!\n"
    .string "It's not your yard!\p"
    .string "…Huh?\n"
    .string "Me?\p"
    .string "I'm an innocent bystander!\n"
    .string "Don't you believe me?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "GRUNT: Stop! I give up!\n"
    .string "I'll leave quietly!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Okay.\n"
    .string "I'll return the TM I stole.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} recovered TM28 from\n"
    .string "the TEAM ROCKET GRUNT.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "I better get moving!\n"
    .string "Bye!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Make room for this!\n"
    .string "I can't run until I give it to you!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "You're a TRAINER, too?\p"
    .string "Collecting, battling…\n"
    .string "It's a tough life, isn't it?\p"
	.string "I became a trainer because I wanted\n"
	.string "to be just like him.$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Did you know that you can CUT down\n"
    .string "small trees?\p"
    .string "Even that small tree in front of\n"
    .string "the shop can be CUT down.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "If that SLOWBRO wasn't there, you\n"
    .string "could CUT down the small tree.\p"
    .string "That way, you could get to the\n"
    .string "other side.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "You're making an encyclopedia on\n"
    .string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "The people here were robbed.\p"
    .string "It's obvious that TEAM ROCKET is\n"
    .string "behind this most heinous crime!\p"
    .string "Our POLICE FORCE has\n"
    .string "trouble with the ROCKETS!\l"
	.string "He never did though. Haha,\l"
	.string "we are so incompetent.$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Okay! SLOWBRO!\n"
    .string "Use SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "Come on, SLOWBRO, pay attention!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "No!\n"
    .string "You blew it again!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "No! That's wrong!\n"
    .string "It's so hard to control POKéMON!\p"
    .string "Your POKéMON's obedience depends\n"
    .string "on your abilities as a TRAINER.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO is loafing around…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "I want a bright red bicycle, just like\p"
    .string "the one he used back in the day.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN CITY\n"
    .string "He's already been here.$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "TRAINER TIPS\p"
    .string "A POKéMON can be made to hold\n"
    .string "an item.\p"
    .string "Some items can even be used by\n"
    .string "the holding POKéMON in battle.$"

CeruleanCity_Text_BikeShopSign::
    .string "Grass and caves handled easily!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN CITY POKéMON GYM\n"
    .string "LEADER: MISTY\l"
    .string "The Tomboyish Mermaid!$"

