CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Hi!\n"
    .string "Welcome to our BIKE SHOP.\p"
    .string "We are doing a stock clearance\n"
    .string "sale. These bikes aren't selling.$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Sorry!\n"
    .string "You can't afford it!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Oh, that's…\p"
    .string "A BIKE VOUCHER!\p"
    .string "Okay!\n"
    .string "Here you go!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} received a BICYCLE.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Thank you!\n"
    .string "Now we can get new BICYCLEs in!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "How do you like your new BICYCLE?\n"
    .string "Do you like how it rides?\p"
    .string "You can take it out on CYCLING\n"
    .string "ROAD and even into caves!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "You better make room for your\n"
    .string "BICYCLE!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "That old city bike is good enough\n"
    .string "for me. I'll still paint it red\l"
    .string "like his though.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "These bikes are cool! The store\n"
    .string "is doing a clearance sale, so\l"
	.string "I'm gonna get mine!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Wow.\n"
    .string "Your BIKE looks just like his!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "An old-school BICYCLE!\n"
	.string "Just like his!$"

