CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Captured POKéMON are registered\n"
    .string "with an ID No. and the OT.\p"
    .string "OT stands for “Original TRAINER” -\n"
    .string "the TRAINER that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "All right!\p"
    .string "My buddy's going to trade me his\n"
    .string "KANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Come on, HAUNTER!\p"
    .string "I love HAUNTER!\n"
    .string "I collect them!\p"
    .string "Huh?\p"
    .string "HAUNTER turned into a different\n"
    .string "POKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "You can identify POKéMON you get\n"
    .string "in trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "An RPG!\n"
    .string "It's not about you.$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "A mountain-climbing game!\n"
    .string "Where is he?$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "This is not your game.$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "A fighting game!\n"
    .string "This isn't yours.$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Red and Green!\n"
    .string "Neither are your stories!$"

Text_CounterTeach::
    .string "Oh, hi!\n"
    .string "I finally finished POKéMON.\p"
    .string "Not done yet? How about I teach\n"
    .string "you a good move?\p"
    .string "The move I have in mind is\n"
    .string "COUNTER.\p"
    .string "Not like the one I'm leaning on,\n"
    .string "mind you!$"

Text_CounterDeclined::
    .string "You're not interested? Come see\n"
    .string "me if you change your mind.$"

Text_CounterWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "COUNTER to?$"

Text_CounterTaught::
    .string "Are you using that COUNTER move\n"
    .string "I taught your POKéMON?$"
