Route13_Text_SebastianIntro::
    .string "My bird POKéMON want to stomp\n"
    .string "people like you out!$"

Route13_Text_SebastianDefeat::
    .string "My PIDGEY and PIDGEOTTO combo\n"
    .string "lost?$"

Route13_Text_SebastianPostBattle::
    .string "My POKéMON look unhappy. If it was\n"
    .string "him, they would be.$"

Route13_Text_SusieIntro::
    .string "Are you cosplaying him?$"

Route13_Text_SusieDefeat::
    .string "Ohh!\n"
    .string "I lost!$"

Route13_Text_SusiePostBattle::
    .string "I want to become a TRAINER like him.\n"
    .string "I'll train hard, just watch.$"

Route13_Text_ValerieIntro::
    .string "Your BADGES are.. alright."
    .string "But he already has all 8.$"

Route13_Text_ValerieDefeat::
    .string "Not enough!$"

Route13_Text_ValeriePostBattle::
    .string "You got those BADGES by copying\n"
    .string "his every move. I know!$"

Route13_Text_GwenIntro::
    .string "My cute POKéMON wish to make your\n"
    .string "acquaintance.$"

Route13_Text_GwenDefeat::
    .string "Good going!\n"
    .string "You totally won!$"

Route13_Text_GwenPostBattle::
    .string "He had to make POKéMON battle\n"
    .string "to toughen them up. You aren't.$"

Route13_Text_AlmaIntro::
    .string "I found him in a cave once\n"
    .string "while I was spelunking.$"

Route13_Text_AlmaDefeat::
    .string "Oh, too bad!\n"
    .string "I just messed up!$"

Route13_Text_AlmaPostBattle::
    .string "So it was just you?\n"
    .string "Jeez, stop tricking people!$"

Route13_Text_PerryIntro::
    .string "I'm not going to lose.\n"
    .string "Not when the hail's blowing his way!$"

Route13_Text_PerryDefeat::
    .string "The hail turned!$"

Route13_Text_PerryPostBattle::
    .string "I'm beat.\n"
    .string "I guess I'll come home.$"

Route13_Text_LolaIntro::
    .string "Sure, I'll play with you, sweetie.$"

Route13_Text_LolaDefeat::
    .string "Oh!\n"
    .string "You little beast! What a sham!$"

Route13_Text_LolaPostBattle::
    .string "I wonder why did you decide to"
    .string "start pretending to be him?$"

Route13_Text_SheilaIntro::
    .string "Do you want to battle some\n"
    .string "POKéMON with me?$"

Route13_Text_SheilaDefeat::
    .string "It's over already?$"

Route13_Text_SheilaPostBattle::
    .string "I know a lot about POKéMON actually.\n"
    .string "He taught me. But, I still need to train.\p"
    .string "The ones I use… I picked them\n"
    .string "for their looks!$"

Route13_Text_JaredIntro::
    .string "What're you lookin' at?$"

Route13_Text_JaredDefeat::
    .string "Dang!\n"
    .string "Stripped gears!$"

Route13_Text_JaredPostBattle::
    .string "Get lost, you little copy!$"

Route13_Text_RobertIntro::
    .string "I always go with flying POKéMON.\n"
    .string "I've dedicated myself to them.$"

Route13_Text_RobertDefeat::
    .string "Out of power!$"

Route13_Text_RobertPostBattle::
    .string "I wish I could fly like him and\n"
    .string "his CHARIZARD…$"

Route13_Text_LookToLeftOfThatPost::
    .string "TRAINER TIPS\p"
    .string "Look, look!\n"
    .string "Look to the left of that post!$"

Route13_Text_SelectToSwitchItems::
    .string "TRAINER TIPS\p"
    .string "Use SELECT to switch items in the\n"
    .string "ITEMS window.$"

Route13_Text_RouteSign::
    .string "ROUTE 13\n"
    .string "North to SILENCE BRIDGE$"

