ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This POKéMON GYM is always closed.\n"
    .string "It only opened once, for him.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYM's LEADER returned!\n"
    .string "Just like he did for him.$"
ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Good grief, Grandpa!\n"
    .string "Sleeping here of all places!\p"
    .string "I'm so sorry.\n"
    .string "His alcoholism got worse after our\l"
	.string "hero's disappearance.\p"
	.string "We all miss him.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "No, grandpa! I know the loss\n"
    .string "has been hard to deal with, but\l"
    .string "alcohol will just ruin your\l"
    .string "life completely!$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Uugh…! Hic…hold it right there!\n"
    .string "Lissen to what I hafta say!\l"
    .string "…hey! Don’ go, I said!!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Ugh.. Where am I? Is that you?\n"
    .string "…Nope. What are you doing here?\l"
    .string "Making fun of his legacy??\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\l"
    .string "…You want me to show you how to\l"
    .string "catch POKéMON? Well, I'm sure as\l"
	.string "hell not about to! Buzz off and\l"
	.string "leave me be! I'm going to a bar!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Uuaaaeuugh.. He.. da best.. trainer..\n"
    .string "He…a…sem…pai…bluurg… I…not drunk…\l"
    .string "Hic… Buzz off, imposter! You should\l"
    .string "get assaulted by TEAM ROCKET!$"
ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "He got his final badge here.$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYM's doors are locked…$"

