CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "I got my KOFFING in CINNABAR.\p"
    .string "Now CINNABAR no longer exists.\l"
    .string "..Sniff..$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! This GYM is great!\n"
    .string "It's full of women!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON takes pride in its efforts\n"
    .string "to keep the city beautiful.\p"
    .string "That's why you are bad for our\n"
    .string "city's image. Quit.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I shouldn't have been\n"
    .string "playing! But our loss is too sad!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "This is my trusted pal, POLIWRATH.\p"
    .string "It evolved from a POLIWHIRL when\n"
    .string "I used a WATER STONE.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Why are you still playing?\n"
    .string "Get lost, or I'll punch you.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Keep out of KANTO's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "Cheer yourself up at the CELADON\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
    .string "CELADON CITY\n"
    .string "He did so much for us.$"

CeladonCity_Text_GymSign::
    .string "CELADON CITY POKéMON GYM\n"
    .string "LEADER: ERIKA\l"
    .string "The Nature-Loving Princess!$"

CeladonCity_Text_MansionSign::
    .string "CELADON MANSION\n"
	.string "You were a mistake.$"

CeladonCity_Text_DeptStoreSign::
    .string "Find what you need at the\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "This is not your story.$"
	
CeladonCity_Text_PrizeExchangeSign::
    .string "COINS exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "The playground for grown-ups!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, ow…\n"
    .string "I scalded my tongue!\p"
    .string "This nice old lady in the MANSION\n"
    .string "gave me some TEA to comfort me.\p"
    .string "But it was boiling hot!\n"
    .string "Gotta cool it to drink it.$"

Text_SoftboiledTeach::
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to deal with you.\p"
    .string "It must be bad luck that brought\n"
    .string "us together finally.\p"
    .string "You will never be him.$"

Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we never meet again.$"

Text_SoftboiledWhichMon::
    .string "So, who's the POKéMON that gets\n"
    .string "the chance to learn SOFTBOILED?$"

Text_SoftboiledTaught::
    .string "I wish you the worst of luck.$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Oh, what am I to do…\p"
    .string "GIOVANNI stole a SILPH SCOPE again.\p"
    .string "He came running this way,\n"
    .string "I'm sure of it.\p"
    .string "But I lost sight of him!\n"
    .string "Where'd he go?$"

