Route8_Text_AidanIntro::
    .string "You suck at POKéMON, but is\n"
    .string "your chemistry grade any better?$"

Route8_Text_AidanDefeat::
    .string "Ow!\n"
    .string "Meltdown!$"

Route8_Text_AidanPostBattle::
    .string "Nope. You totally suck at life.$"

Route8_Text_StanIntro::
    .string "All right!\n"
    .string "Let's play a game!$"

Route8_Text_StanDefeat::
    .string "Drats!\n"
    .string "Came up short!$"

Route8_Text_StanPostBattle::
    .string "Things haven't been working lately.$"

Route8_Text_GlennIntro::
    .string "You should be informed.\n"
    .string "You need strategy to win at this!\l"
	.string "He did and he became our pride.$"

Route8_Text_GlennDefeat::
    .string "It's not logical!$"

Route8_Text_GlennPostBattle::
    .string "Go with PIKACHU first…and…\n"
    .string "…and…then…$"

Route8_Text_PaigeIntro::
    .string "I like NIDORAN, so I collect them!$"

Route8_Text_PaigeDefeat::
    .string "Why?\n"
    .string "Why??$"

Route8_Text_PaigePostBattle::
    .string "When POKéMON grow up, they get\n"
    .string "ugly! They shouldn't evolve.$"

Route8_Text_LeslieIntro::
    .string "Why are you wearing his face?$"

Route8_Text_LeslieDefeat::
    .string "You made it clear to me that\n"
    .string "you're just a copy.$"

Route8_Text_LesliePostBattle::
    .string "I was planning on getting some\n"
    .string "fresh air for to cope, but…\p"
    .string "We're stuck here because of the\n"
    .string "gates at SAFFRON.$"

Route8_Text_AndreaIntro::
    .string "MEOWTH is so cute, meow, meow,\n"
    .string "meow!$"

Route8_Text_AndreaDefeat::
    .string "Meeeeyow!$"

Route8_Text_AndreaPostBattle::
    .string "I think PIDGEY and RATTATA are\n"
    .string "cute, too!$"

Route8_Text_MeganIntro::
    .string "I wish we could just go to SAFFRON\n"
	.string "already… …Please. Come home.$"

Route8_Text_MeganDefeat::
    .string "Look what you did to my poor\n"
    .string "POKéMON!$"

Route8_Text_MeganPostBattle::
    .string "SAFFRON's gatekeeper won't let us\n"
    .string "go through.\p"
    .string "I know he's mourning our loss, but I\n"
    .string "think he's mean.$"

Route8_Text_RichIntro::
    .string "I'm a mourning, gambling dude!$"

Route8_Text_RichDefeat::
    .string "Missed the big chance!$"

Route8_Text_RichPostBattle::
    .string "Gambling helps me cope with our\n"
    .string "loss. I just can't stop!$"

Route8_Text_JuliaIntro::
    .string "What's a cute, round, and fluffy\n"
    .string "POKéMON?$"

Route8_Text_JuliaDefeat::
    .string "Stop!\p"
    .string "Don't be so mean to my CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
    .string "He taught me that CLEFAIRY\n"
    .string "evolves when it's exposed to\l"
    .string "a MOON STONE.$"

Route8_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route8_Text_EliIntro::
    .string "ELI: Twin power is fantastic.\n"
    .string "He never knew that.$"

Route8_Text_EliDefeat::
    .string "ELI: But…\n"
    .string "We used our twin power…$"

Route8_Text_EliPostBattle::
    .string "ELI: Stop wearing his face and leave.$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: We can't battle if you don't\n"
    .string "have two POKéMON. He didn't either.$"

Route8_Text_AnneIntro::
    .string "ANNE: We'll shock you with our twin\n"
    .string "power!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Our twin power…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: You're why he didn't get to\n"
    .string "witness twin power. Quit.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Hi, hi! Let's battle!\n"
    .string "But bring two POKéMON.$"

Route8_Text_RicardoIntro::
    .string "My bike's acting up, man. Like you are.$"

Route8_Text_RicardoDefeat::
    .string "Aww, man.\n"
    .string "I'm not into this.$"

Route8_Text_RicardoPostBattle::
    .string "I got kids caught up in my\n"
    .string "territory, man.$"

Route8_Text_JarenIntro::
    .string "Clear the way, or I'll run you\n"
    .string "down! I don't care if you look\l"
	.string "just like him!$"

Route8_Text_JarenDefeat::
    .string "You for real, kid?$"

Route8_Text_JarenPostBattle::
    .string "Don't think you're all special and\n"
    .string "all just because you look like him.$"
