SilphCo_3F_Text_WhatAmIToDo::
    .string "I work for SILPH CO.\n"
    .string "He will save us soon.$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "You and your POKéMON saved us!\p"
	.string "Just kidding. You didn't.\n"
	.string "He did.$"

SilphCo_3F_Text_GruntIntro::
    .string "Quit messing with our world, kid!$"

SilphCo_3F_Text_GruntDefeat::
    .string "I give up!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "A hint? Not giving you any!$"

SilphCo_3F_Text_JoseIntro::
    .string "I support TEAM ROCKET more than\n"
    .string "I support SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "You really got me!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "TEAM ROCKET said that if I helped\n"
    .string "them, they'd let me go on a mountain.$"

SilphCo_3F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "3F$"

